### ISSUE TITLE
Make ordinals.com beautiful

### ISSUE THREAD

**Issue by casey** [casey/ord#1006]
Not sure how much we should prioritize this. Making inscriptions desirable might be secondary to making sure that there's a market.

Some different NFT markets for visual reference:
- https://superrare.com/
- https://foundation.app/
- https://knownorigin.io/
- https://deca.art/
- https://gallery.so/
- https://objkt.com/
- https://www.dns.xyz/

**Comment by rot13maxi** [comment]
I think this is important. non-ideological users who are looking for the best technology to build their NFTs will be comparing fit-and-finish across marketplaces/explorers. Having an explorer that looks more expert-friendly might scare away creators or collectors who would otherwise be super happy with ordinals

**Comment by casey** [comment]
@rot13maxi Agreed on all points.

How would you prioritize the following:

- Making ordinals.com beautiful
- Launching on mainnet
- Helping the first market form

**Comment by rot13maxi** [comment]
That's probably the right order. reasonable people could disagree about 1 & 2, but I think being able to announce "mainnet is live!" and having people go to a really slick ordinals-explorer is a better plan than launching on mainnet, and then later announcing "now ordinals.com is slick!"

**Comment by casey** [comment]
> That's probably the right order. reasonable people could disagree about 1 & 2, but I think being able to announce "mainnet is live!" and having people go to a really slick ordinals-explorer is a better plan than launching on mainnet, and then later announcing "now ordinals.com is slick!"

Good point, I definitely agree.

**Comment by casey** [comment]
Definitely could still use some work, but I think this is mostly done.
