### ISSUE TITLE
Consider exposing inscription numbers

### ISSUE THREAD

**Issue by casey** [casey/ord#1024]
We currently store inscriptions in the index under an incrementing inscription number key, starting at 0, giving all inscriptions a unique, small integer that unambiguously refers to them.

We could expose this in the interface:
- Show inscription number in /inscription, which would let you easily see which of two inscriptions was first
- Allow short links using /inscription/number
- Allow sending by inscription number

There are issues though. You can only determine an inscriptions number using a full index of all inscriptions, so light clients would be unable to determine inscription numbers, and if the set of inscriptions changes for some reason, all inscription numbers would change. Also, inscription numbers aren't stable across reorgs.

However, having short, unique, identifiers would be valuable, so I'm on the fence about this.

**Comment by rot13maxi** [comment]
what would this mean?

**Comment by casey** [comment]
I've been dumping random inscrutable notes in issues, gotta stop doing that! I fleshed up the issue, have another look.
