### ISSUE TITLE
Ordinals nostr chat

### ISSUE THREAD

**Issue by casey** [casey/ord#1041]
I dunno, seems like nostr is the place to be.

**Comment by casey** [comment]
Not automatically, but you could certainly send someone a lightning invoice and then send them an inscription if they paid it.

**Comment by raphjaph** [comment]
I think you could do this trustlessly with [submarine swaps](https://docs.lightning.engineering/the-lightning-network/multihop-payments/understanding-submarine-swaps)

**Comment by casey** [comment]
Good thought! I think you're right. Pretty sick.

**Comment by casey** [comment]
I think we'll have our hands full with the Discord.
