### ISSUE TITLE
Quickly browse through all inscriptions

### ISSUE THREAD

**Issue by casey** [casey/ord#1052]
For easy browsing, it would be nice to be able to quickly navigate through multiple inscriptions. One way of doing this is to add the ability to navigate to previous/next inscriptions on the /inscription page.

**Comment by rot13maxi** [comment]
would also be great to be able to see a catalog of all inscriptions, right now it looks like you only see the most recent 8

**Comment by casey** [comment]
Definitely, see #1051. We have the `/inscriptions` page, but it's just a list of IDs right now. I want to reuse the styling from the home page and display a grid of previews on `/inscriptions`.

**Comment by raphjaph** [comment]
This probably goes hand in hand with inscription numbers: `/inscription/3` next `/inscription/4`.

#1024

**Comment by casey** [comment]
> This probably goes hand in hand with inscription numbers: /inscription/3 next /inscription/4.

Not necessarily, the index can look up the current and next inscription IDs via number, but then populate the prev and next links with the IDs, so they're never exposed to users.

**Comment by raphjaph** [comment]
True, but if we decide to expose inscription numbers we could design it this way.

**Comment by casey** [comment]
Done in #1193! /inscription now has previous and next links that appear on hover over the left and right of the inscription image. Additionally, left and right arrow now go to the previous and next item on /inscription, /sat, and /block. Eventually, if we number transactions as in #1192, we can make this work for transactions.
