### ISSUE TITLE
Avoid scary firewall popup while developing

### ISSUE THREAD

**Issue by casey** [casey/ord#1068]
Could we switch the server address from `0.0.0.0:80` to `127.0.0.1:80` to avoid the scary firewall popup on macos?

**Comment by raphjaph** [comment]
Tried to do this but my mac doesn't allow me to listen on 127.0.0.1:80 with sudo. Strangely enough it allows me to listen on 0.0.0.0:80 without sudo. The firewall pop up appears but I can connect from localhost without clicking on it. I tested with with netcat.

Doesn't work:
```
nc -l 127.0.0.1 80
nc: Permission denied
```

Works:
```
 nc -l 0.0.0.0 80

```
works

**Comment by casey** [comment]
I noticed that it requires sudo for 127.0.0.1 and not 0.0.0.0, super weird. Maybe we'll have to switch to 127.0.0.1:8000. Ports below 1024 are "well known ports", and unixes require admin privs to bind to them.

A good first step for this issue would be to figure out which test, in particular, is causing this issue. It might just be one test, and then we can pass different --address / --http-port flags in that one test to fix the issue.
