### ISSUE TITLE
Post new inscriptions to RSS feed

### ISSUE THREAD

**Issue by raphjaph** [casey/ord#1070]
Makes it easy to write bots and integrate into social media feeds. You could also do this with webhooks but RSS seems like such a simple solution.

**Comment by casey** [comment]
We could also post to nostr. Less reach, but has a cool, underground flavor.

**Comment by raphjaph** [comment]
Yea, definitely have to do that as well. There is also a relay that relays RSS feeds: <https://github.com/fiatjaf/rsslay>
