### ISSUE TITLE
Test importdescriptors: https://github.com/rust-bitcoin/rust-bitcoincore-rpc/issues/264

### ISSUE THREAD

**Issue by casey** [casey/ord#1074]

**Comment by raphjaph** [comment]
I tried to do this today but couldn't figure out which code you uploaded to crates.io for the `ord-bitoincore-rpc` crate. Compiling `ord` with the master and ord branch of `casey/rust-bitcoincore-rpc` threw a bunch of errors. I'm probably doing something wrong with the patch command though.

**Comment by casey** [comment]
Can you open a draft PR with the changes you made so I can take a look?

**Comment by casey** [comment]
Whoops, didn't mean to close.

**Comment by raphjaph** [comment]
#1075
