### ISSUE TITLE
Stable identity for creators and collectors

### ISSUE THREAD

**Issue by batcavekid** [casey/ord#1094]
Give inscribers and collectors the option of a stable identity. This could be pseudonymous or doxxed, at user's discretion.

POSSIBLE IMPLEMENTATIONS: 
- prime inscriptions: a specific inscription that represents an individual, organization, or collection
- publish pubkey (optionally)
- other (...)

PRIVACY:
- Need not be IRL identiy (pseudonyms would have similar benefits)
- To preserve privacy, perhaps this should be opt-in
- UX consideration --> how best to communicate the consequences of publicizing to users

**Comment by casey** [comment]
I think this is already covered by #783 and #784, feel free to comment on those issues if there's something missing.
