### ISSUE TITLE
Run a testnet instance

### ISSUE THREAD

**Issue by casey** [casey/ord#1105]
Testnet is chaos, so it's be useful to run a testnet instance for testing.

**Comment by casey** [comment]
I tried to run a testnet instance on a 4 gig Linode instance, but it ran out of memory around block 1.3 million T_T We probably need at least 8 gigabytes of ram.

**Comment by casey** [comment]
Trying again with an 8GB instance.

**Comment by casey** [comment]
Syncing: https://testnet.ordinals.com/

**Comment by casey** [comment]
IT LIVES!

**Comment by qalqi** [comment]
Currently, testnet is out of sync

**Comment by Sirgulator** [comment]
related to #1727
