### ISSUE TITLE
Return URLs for 'ord wallet inscriptions'

### ISSUE THREAD

**Issue by batcavekid** [casey/ord#1112]
Less cumbersome than copy pasting a partial url.

Example:

`ord wallet inscriptions --urls`

The urls would link from terminal to the inscription page on ordinals.com.

In a world with multiple platforms/sites: 

`ord wallet inscriptions --urls {platformName}`

Perhaps users could give their inscriptions names (locally or later on via a field) that can be returned as hyperlinks: 

```
rarepepe_1
haiku
exotic_generative_art_collection27
```

**Comment by casey** [comment]
Done!
