### ISSUE TITLE
Update url for installation in docs

### ISSUE THREAD

**Issue by batcavekid** [casey/ord#1113]
This returns a 404 error:

`curl --proto '=https' --tlsv1.2 -fsLS https://ordinals.com/install.sh | bash -s`

[Link to page in docs](https://docs.ordinals.com/guides/inscriptions.html#installing-ord)

**Comment by raphjaph** [comment]
works on my machine

**Comment by casey** [comment]
Works on my machine, can you paste the full error code?

**Comment by casey** [comment]
Whoops, didn't mean to close.

**Comment by casey** [comment]
I believe the install script is still broken, see this PR: https://github.com/casey/ord/pull/1120

**Comment by casey** [comment]
We still don't support ARM, but this will give a less confusing error now.
