### ISSUE TITLE
Serve custom fonts for ASCII art

### ISSUE THREAD

**Issue by batcavekid** [casey/ord#1126]
Example:
![image](https://user-images.githubusercontent.com/8632866/210111535-89a993fe-6fd8-4b60-a0cc-d5f6b884c8d6.jpeg)

**Comment by casey** [comment]
It's not possible to distinguish ascii art from non-ascii art, so any custom font would have to be used for all text inscriptions. If an artificer wants to use a custom font, they'll need to use HTML.

**Comment by casey** [comment]
> Maybe we could inscribe .ttf font files and reference them with html inscriptions to import the font. I don't know if this can solve for the need to serve the font but I'll look into it.

Yah, definitely. This should be possible once we allow multi-file inscriptions.
