### ISSUE TITLE
Add send by satpoint test

### ISSUE THREAD

**Issue by casey** [casey/ord#1202]

**Comment by null-ish** [comment]
@casey was this ever added?


`ord --wallet binance wallet send PUBLIC_KEY 123456sats --satpoint TXID:OUPUT:0 --fee-rate 15`

UTXO being used has no inscriptions in it. Only a lot of sats/sat ranges.

Attempting to use satpoint parameter to target 123456sats being sent from the first sats in the UTXO, and fee being taken from the last sats of the UTXO.

Any input? The above returns:

```
Found argument '--satpoint' which wasn't expected, or isn't valid in this context
If you tried to supply `--satpoint` as a value rather than a flag, use `-- --satpoint`
```
