### ISSUE TITLE
Accept donations for ord development

### ISSUE THREAD

**Issue by batcavekid** [casey/ord#1254]
An easy and standard way to support the ongoing development of ord, which is fully OSS, and beneficial to various stakeholders in the BTC and digital art communities.

**Comment by casey** [comment]
I'm actually leaning towards not doing this right now. I've looked at other projects that accept donations, and even successful ones tend to get very little, so it's very low priority.

**Comment by dude513** [comment]
Just an idea is to allow donations while creating an inscription, then create a separate list of inscriptions where those with most funds donated to ord will be on top.  It can stimulate people to donate and I believe it can also increase the value of a particular inscription. @casey

**Comment by casey** [comment]
I think what I'd like is actually to add a donate command: `ord wallet donate <INSCRIPTION_ID>`, which would donate an inscription to the project.

**Comment by casey** [comment]
Just opened https://github.com/casey/ord/issues/1570 to track this.
