### ISSUE TITLE
--dry-run should print out unsigned transactions

### ISSUE THREAD

**Issue by casey** [casey/ord#1263]
For both `ord wallet send` and `ord wallet inscribe`

**Comment by raphjaph** [comment]
Ok, I'll do it like that for #808

**Comment by casey** [comment]
It might be tricky, I don't know if transactions implement `Serialize`. If they don't, we probably want to punt on it for now.

**Comment by casey** [comment]
I'm actually not sure if this is useful. Closing for now.
