### ISSUE TITLE
Consider supporting additional video format: H.264 codec in MP4 container

### ISSUE THREAD

**Issue by EvanWinget** [casey/ord#1350]
Browsers:
macOS Safari Version 16.2 (18614.3.7.1.5)
iOS Safari (whatever version is on an iPhone running iOS 16.1.2)

Inscription:
https://ordinals.com/inscription/fdcf0b5725301493f3bbb0564d9a1ecac9ab5baa0d3c6523ca77186184f3c3fai0

Video player appears but shows black background and zero second video. 

After a bit of searching, I think that this is a limitation of Safari, in which case this issue can be closed... Might be worth noting somewhere though.

**Comment by casey** [comment]
This is a Safari issue, but I think it's worth keeping this issue open. We could support H.264 in MP4, which is worse but works everywhere.

**Comment by cryptoquick** [comment]
I think it's best to not overthink it. Since you have preview, it can be double-checked beforehand, at least.

**Comment by casey** [comment]
Here's an example of an illicit MP4 inscription: https://ordinals.com/content/2b6421c68f123e6332700133d842e14346cf2bdcda5c660465c4b3ee0f78284ei0
