### ISSUE TITLE
Re-enable skipping transactions below first inscription height

### ISSUE THREAD

**Issue by casey** [casey/ord#1364]
I'm not sure how to do this. We'd need to get UTXO set values when we hit inscriptions. Maybe we only need UTXO values for transactions that contain inscriptions, in which case maybe the impact of fetching input transactions from bitcoin core is low.

We can also use the new verbosity level of getrawtransaction to return the value of all inputs in one go: https://github.com/bitcoin/bitcoin/issues/23319

**Comment by raphjaph** [comment]
- Check wether `getrawtransaciton --verbose` is in newest Bitcoin Core release
- Start with PR agains rust-bitcoincore-rpc

**Comment by raphjaph** [comment]
Waiting for new release of Bitcoin Core

**Comment by andrewtoth** [comment]
Could we not just use `getblock` with `verbosity=3` to get the blocks with all input values?

**Comment by casey** [comment]
> Could we not just use `getblock` with `verbosity=3` to get the blocks with all input values?

I suspect that this would be really slow. `verbosity=3` includes a lot of extra data. However, it might be good to benchmark this and make sure it's the case.

**Comment by andrewtoth** [comment]
Also, if we are going the route of calling `getrawtransaction` individually vs one `getblock verbosity=3`, then we should probably be using `async`. We can then hit the REST endpoint concurrently with a `join_all` instead of sequentially. We could potentially batch the `getrawtransaction` calls but `rust-bitcoincore-rpc` doesn't support the batching feature :/.

**Comment by andrewtoth** [comment]
Ok I figured it out. Managed to sync by combining p2p and REST and reverting #1357 in 1:06. I think we can turn this back on :).

Batching calls would overwhelm bitcoind, and `getblock verbosity=3` is slower than just synchronously fetching missing inputs via REST.

**Comment by andrewtoth** [comment]
With latest REST PR using hyper myself on Linux and @so7ow on Mac synced in under an hour 🚀 https://github.com/casey/ord/issues/1648#issuecomment-1427946904.

**Comment by andrewtoth** [comment]
Check out https://github.com/casey/ord/pull/1759. It still hasn't been explained why skipping transactions were removed, but that PR manages to sync efficiently without having all inputs.
