### ISSUE TITLE
Stats page - Total fees paid

### ISSUE THREAD

**Issue by cryptoquick** [casey/ord#1394]
It'd be neat to have a stats page, to show how many bytes have been inscribed so far, to trigger the haters. But also, to mollify the haters, it's important to show how many sats were given to miners for the privilege of a landing bytes on the most important blockchain there ever was or will be. Then you could multiply the fees times the price, and you have a nice figure to say "this is money miners wouldn't have gotten if people didn't find value in ordinals"

Anyway, just a thought.

**Comment by casey** [comment]
Definitely! See https://github.com/casey/ord/issues/1371. We also want to record the total size of all inscriptions. Although the haters probably wouldn't like that.

**Comment by cryptoquick** [comment]
lol! This is the second time we've opened the same issue within ~24 hours of each other :joy_cat:

**Comment by casey** [comment]
Degenerate minds think alike!
