### ISSUE TITLE
 Show Address/ScriptPubKey that send funds to the commit address in the Inscription detail page

### ISSUE THREAD

**Issue by rot13maxi** [casey/ord#1423]
If someone is minting a collection of inscriptions, people will want to know which individual inscriptions were minted as part of that collection. Ultimately there's a provenance issue: how do you know where inscriptions came from? On other networks, there's a notion of an "issuer address", and you can just say "all the artifacts issued by this address are the ones that I'll seek out". We don't _really_ have that in the UTXO model. Maybe a way to get something similar would be to re-use taproot addresses/keys for the funds that are on the input side of the commit transaction. That way I can say "mint these 10 artifacts" and even if they're minted over time or across blocks, they still have a common ancestor.

Maybe the right answer here is to put a signature in the inscription metadata. Just trying to brainstorm things that won't affect the encoding or envelope.

**Comment by casey** [comment]
We're actually thinking about doing this a different way, check out #783. The issue with an address is that it can't be changed later, and that it doesn't have any fun metadata (like a picture, etc.). So the idea is that we use inscriptions. You put an inscription as an input to the reveal transaction, which makes it a parent of the new inscription. This parent/child relationship will be visible on the block explorer, allowing you to navigate up and down, and you can use an inscription to represent you, the creator, or a collection.
