### ISSUE TITLE
i0 at the end of each tx

### ISSUE THREAD

**Issue by dude513** [casey/ord#1426]
What is the reason of the embedded string "i0" at the end of each txid in the id section?

![image](https://user-images.githubusercontent.com/123891835/215743020-7cd8bb04-591e-4e08-a070-b3af48c0a29e.png)

**Comment by hbeckeri** [comment]
this is to say which output index the token is - they are all currently index 0 but there is no reason they couldnt be in other indexes

**Comment by casey** [comment]
Actually, it's the index of the inscription in the transaction. Currently, it's only possible to make one inscription per transaction, so they're all `TXIDi0`, but we're going to relax that in future.
