### ISSUE TITLE
Default wallet derivation path?

### ISSUE THREAD

**Issue by windsok** [casey/ord#1427]
I'm trying to import my `ord` wallet into Sparrow Wallet just to be able to inspect some things and look at transactions.

I tried using a Single Sig P2TR wallet using BIP39 and the 12 words that were supplied via the `ord` cli when my wallet was created.

The default `m/86' /0' /0'` derivation path did not seem to work, or generate the same addresses as `ord` has been using, so I'm wondering if `ord` is using a different derivation path? Thanks!

**Comment by casey** [comment]
Off the top of my head, what you said sounds right. Try using `bitcoin-cli -rpcwallet=ord listdescriptors`, it should print out the descriptors.

**Comment by windsok** [comment]
hmm yep the descriptor output does show `[<fingerprint>/86' /0' /0']`

In Sparrow the fingerprint and xpub generated from the BIP39 seed appears different but I'm unsure why

**Comment by casey** [comment]
Here's our derivation code, maybe we're doing something weird: https://github.com/casey/ord/blob/9f5d864421d3beae50fa5115cc5db94117fd519b/src/subcommand/wallet.rs#L123

**Comment by vicariousdrama** [comment]
Im able to do this in Sparrow, but the receive address that ord gives is the first change address in the wallet, not the receive address.  Still valid, but seemed odd

**Comment by windsok** [comment]
@vicariousdrama you were able to see all your transactions from your ord wallet in sparrow?

hmm maybe it's possible I wrote down the wrong BIP39. I'll do some more testing with a new ord wallet on a different machine.

**Comment by windsok** [comment]
OK turns it this was totally a me problem, I've tried again and was able to successfully import the ord wallet into Sparrow

**Comment by casey** [comment]
Awesome, great to hear! I was worried we were doing something weird, it wouldn't be the first time 😅

**Comment by shimmydz** [comment]
> 

![Screenshot_20230201-234806](https://user-images.githubusercontent.com/60141796/216235633-18f26889-a853-4f30-b522-046d82fb782b.png)

**Comment by shimmydz** [comment]
Y'all fags

**Comment by shimmydz** [comment]
@google.com/fagfucks
