### ISSUE TITLE
Sending coins from the wallet to an address is not working

### ISSUE THREAD

**Issue by hbeckeri** [casey/ord#1435]
running `ord wallet send <ADDRESS> 12345` is giving me the following error:

```
error: Invalid value "12345" for '<OUTGOING>': invalid number format

For more information try --help
```

Am i doing something wrong? Im trying to send coins to a new address

**Comment by casey** [comment]
Outgoing amounts require a unit, so `ord wallet send <ADDRESS> 12345sats` or `12345btc`
