### ISSUE TITLE
Error: "could not get change address from wallet"

### ISSUE THREAD

**Issue by batcavekid** [casey/ord#1440]
Think I see this sometimes when `ord wallet receive` or maybe other commands, will try to replicate ASAP, sorry I don't have more detail at hand yet.

**Comment by casey** [comment]
No worries! Details are great, but incomplete reports are still good. Other users can add details, which helps to get to the bottom of things. And we can just close if we can't replicate it.

**Comment by casey** [comment]
I'm going to go ahead and close this, since there haven't been other reports of it being an issue. Please feel free to reopen!
