### ISSUE TITLE
I'm an expert in Reddit marketing with 480 KARMA and can promote your NFTs on reddit in cryptpmoonshots I make great NFTsmoonshots (CMS) posts as well as other 10 subreddit posts which I also provide upvotes and cms Trending in the top hot session...

### ISSUE THREAD

**Issue by la-christus** [casey/ord#1445]
I'm an expert in Reddit marketing with 480 KARMA and can promote your NFTs on reddit in cryptpmoonshots I make great NFTsmoonshots (CMS) posts as well as other 10 subreddit posts which I also provide upvotes and cms Trending in the top hot session...

**Comment by casey** [comment]
Thanks for the offer, but our marketing budget is $0.
