### ISSUE TITLE
Prebuilt Binary Fails with GLIBC_2.32 not found

### ISSUE THREAD

**Issue by lylepratt** [casey/ord#1457]
When I try to run the pre-built linux binary, it fails with this error:
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /bin/ord)
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /bin/ord)
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /bin/ord)

Looks like I'm running 2.31
```
libc6:
  Installed: 2.31-0ubuntu9.9
  Candidate: 2.31-0ubuntu9.9
```

I'm running Ubuntu 20.04.4 LTS. Guess I need to update, but was just sharing in case you could compile with support for 2.31 in case others have this problem.

**Comment by dude513** [comment]
@lylepratt Please have a look the response here: https://github.com/casey/ord/issues/1430

**Comment by lylepratt** [comment]
yeah I upgraded to 22.04 and am all good. closing this.
