### ISSUE TITLE
Build fails with "No such file or directory"

### ISSUE THREAD

**Issue by hantuzun** [casey/ord#1467]
```
error: couldn't read src/bin/mord --vain.rs: No such file or directory (os error 2)
```

There's no file named mord in src/bin; just main.rs. 

Experiencing at [10f8469a09f601d2ae4939a2d74b0f607782a26b] on macOS with cargo 1.67.0 (8ecd4f20a 2023-01-10).

**Comment by hantuzun** [comment]
I created an empty file at `src/bin/mord` (relative the the project root, and got the same error.

**Comment by hantuzun** [comment]
[975541689acb8374ff41165b94dff826a91c186a] worked. Bisecting...

**Comment by hantuzun** [comment]
Nevermind, that commit (HEAD) worked this time.

**Comment by casey** [comment]
That error is very odd, let me know if you reproduce this.

**Comment by hantuzun** [comment]
Very odd indeed, because I've never seen occurances of mord or vain

**Comment by raphjaph** [comment]
maybe there's something wrong with your shell. It seems like a couple letters got mixed around: `/src/bin/ord/main.rs` does exist
