### ISSUE TITLE
Blog about content and moderation

### ISSUE THREAD

**Issue by casey** [casey/ord#1476]
- not a new problem (be specific)
    - https://www.reddit.com/r/Bitcoin/comments/1bw9xg/data_in_the_blockchain_wikileaks/
  - data is buried in a witness, you don't see it if you run a full node
  - if this is an attack vector on bitcoin, it is a simple and accessible one
  - layer distinction:
    - bitcoin/chain/protocol
    - ord and inscriptions
    - public explorer has responsibilities
    - our personal approach to the website

**Comment by hantuzun** [comment]
There's an opinion piece written for WIRED relevant to this topic: https://www.wired.com/story/why-porn-on-the-blockchain-wont-doom-bitcoin/

**Comment by casey** [comment]
I've kind of given op on blogging, wayyyy to much to do that's higher leverage T_T
