### ISSUE TITLE
Flag to bypass 400,000 W/U limit

### ISSUE THREAD

**Issue by casey** [casey/ord#1488]
Users currently have to modify their clients to do this, good to provide a flag to bypass.

**Comment by hantuzun** [comment]
I suggest not making this even easier for political reasons.

**Comment by rot13maxi** [comment]
depends on #1489 to be useful

**Comment by casey** [comment]
I think we should do this, super easy PR, users want it. 🔥

**Comment by casey** [comment]
If the users want to rip four meggers, then that's what we should let them do. :elmo-burning:

**Comment by casey** [comment]
Done! Bitcoin is the Political.

https://www.youtube.com/watch?v=B5VX6LJKCMc
