### ISSUE TITLE
Please allow API calls to 'known' Bitcoin Blockchain API providers on ordinal.com

### ISSUE THREAD

**Issue by DEFSTALKR** [casey/ord#1508]
Hey Casey, **love** what you have built here!
Over the last 18 months we've devloped an in depth generative musical & visual composition piece of generative works that we're now about to inscribe as a HTML files (1/21), it's vanilla JS & SVG, no external libraries, and comes just under 40kb minified. 
We've managed to make the work evolve in real-time in reaction to the Bitcoin network, forever generating music and visuals based on Bitcoin's blockchain events (halvenings, mining difficulty, time of blocks and much more...) but the issue is, it relies on a single API `blockheight` call so that the work evolves in real time based off of the live blockheight. 

We're just using a basic `https://blockchain.info/q/getblockcount` call to get this data (it also uses blockstream as a fallback if the first fails) but as we've found out since inscribing a 'test' file  two days ago, is that your explorer kills the API call in the work, effectivly making the work redundant through your explorer. 
I completely understand why you would not allow random API calls in HTML files on your site, but I'm wondering if you would possibly consider 'whitelisting' one or a couple of safe and longstanding Bitcoin API provider's calls. 

It could really see some interesting works being inscribed using the Bitcoin network's data! We're under a very strict timeline so reaching out & crossing fingers in hopes you will consider :) :)

If you wish to preview our project please hmu on twitter, discord or telegram @DEFSTALKR.

Much appreciate your consideration and time mate!

**Comment by casey** [comment]
Thanks for the issue! Web requests to third party websites cannot be whitelisted, because if those specific websites go down or change their API, inscriptions that rely on them would break. This will eventually be enabled by #1385, which will give access to specific, local endpoints. #1082 is also related. Sorry this can't be done sooner!

**Comment by DEFSTALKR** [comment]
Thanks for the reply here Casey, we will still be inscribing our work with the API call implemented since the entire work revolves around the current block height, but the good news is; the minified code allows the user to easily enter/replace their own single API link for the `getblockheight` call which future proofs the work. 
The piece also works in an 'offline mode', but just won't be in real time on the explorer page, which is fine for us.

Excited to show the work soon, appreciate your time here. :)

**Comment by DEFSTALKR** [comment]
https://musicnonstop.io/live/COUNTERSOUL.html

Here's the end result. Minified code easily allows the user to switch out the api to their blockheight call of choice :)

Cheers.
