### ISSUE TITLE
message signing and verification

### ISSUE THREAD

**Issue by rot13maxi** [casey/ord#1511]
There are a number of scenarios where someone will want to prove possession of a particular sat:

- prove ownership to a buyer or trade counterparty
- authentication or membership schemes

Given some message, you should be able to do `ord wallet sign <satpoint> <message>` and produce a signature using the ket that controls `satpoint`.

Then, given a message, a signature, and an address, you should be able to do `ord verify <signature> <message> <address>` and have it tell you if the signature is valid.

Note that for keys that control inscribed ordinals, we might need to tweak the pubkey with the taproot spendinfo to get a valid privkey that matches the onchain address.

**Comment by tyjvazum** [comment]
I think this is a great idea. It would enable additional use cases for `ord`. There was an earlier issue about the same feature: [https://github.com/casey/ord/issues/1462](https://github.com/casey/ord/issues/1462)
