### ISSUE TITLE
Improve redb index space usage

### ISSUE THREAD

**Issue by casey** [casey/ord#152]
The index can potentially contain a huge number of entries, so anything that reduces space usage is probably worth doing.

Some ideas:

- Reduce the page size to reduce fragmentation.

- The only operations done with the HEIGHT_TO_HASH table are push and pop. An alternative way to store it would be a file that we simply append hashes to. This would have zero overhead. Unfortunately, the other tables have much more data, so optimizing the height to hash table won't do much good for overall space usage.

- The OUTPOINT_TO_ORDINAL_RANGES table is also only ever appended to. (And when we handle reorgs, things will get removed from the end.) However, unlike HEIGHT_TO_HASH, we need to lookup items by outpoint, instead of by position in the array. If an in-memory BTreeMap or HashMap has less space overhead than a redb table, then we could have a flat file that we push items to, and an in-memory map outpoint to u64 offset in the file. On startup, we would need to rebuild the in-memory map to the contents of the files, but we might be able to minimize space overhead that way.

- We could do something similar for KEY_TO_SATPOINT where we use an in-memory b-tree map that maps keys to offsets into a flat file, and rebuild the map from the file every time we run.

**Comment by casey** [comment]
@cberner This issue has a bunch of random ideas for improving index space usage, although it sounds like it would be improved a lot when the key limit is lifted.

**Comment by cberner** [comment]
Ya, looking at those stats you posted, the key limit seems like the easiest win
