### ISSUE TITLE
Ability to select/sort UTXOs used for inscription

### ISSUE THREAD

**Issue by Jamil** [casey/ord#1525]
So let’s say we fund our wallet with two UTXOs:
UTXO-1: 10,000 sats
UTXO-2: 1,000 sats

And two inscriptions we want to make, one (Inscription A) that requires 5,000 sats and the other (Inscription B) that requires 500.

Let's say we want to submit Inscription B first, or we have some automated logic to do so. And we now we spend UTXO-1 to submit Inscription B. Inscription A cannot be sent now, because we don’t have any UTXOs that are spendable that exceed 5,000 sats.

I took a quick look through the code and it doesn't seem like there's logic to "optimize" UTXO use depending on the total fees (to minimize the amount of "change" given). In the absence of this, maybe being able to explicitly specify which UTXO you'd like to use would be valuable?

**Comment by rot13maxi** [comment]
would the `--satpoint` option do what you want here?

**Comment by Jamil** [comment]
@rot13maxi that works great, thank you for the heads up on this! gonna close this issue then, and for anyone stumbling across this in the future:

```
> ord wallet outputs
abc…xyz:1	345929

> ord wallet inscribe {file} --satpoint abc…xyz:1:0
```
```
