### ISSUE TITLE
Using SVGZ will save more space on chain

### ISSUE THREAD

**Issue by pool2win** [casey/ord#1580]
By providing an option to use SVGZ extension for the svg mime type and changing the webserver's encoding options, we will potentially save a fair bit of space on the chain.

https://stackoverflow.com/questions/1233540/using-svgz-in-html-server

If it sounds worth looking into, I am happy to send a small PR.

**Comment by casey** [comment]
Compression should be orthogonal to formats. We should add a general compression feature, instead of only compressing specific formats. See #891!
