### ISSUE TITLE
`wallet send` with `--dry-run`

### ISSUE THREAD

**Issue by raphjaph** [casey/ord#1597]
Also check whether `--fee-rate works correctly. There have been some reports of not working correctly.

someone did 10.0 but only 4.0 paid

another one with `ord wallet send --fee-rate 20 ...` and paid 4.44

**Comment by rot13maxi** [comment]
great idea

**Comment by casey** [comment]
Anything related to paying the wrong fee would be really good to keep your third eye peeled for. I've only seen one report of it, but https://github.com/casey/ord/issues/1432 was from a user who provided a screenshot, so I'm confident that they ran the command correctly.

**Comment by casey** [comment]
This is a duplicate of #1432, since @droplister was able to root cause it.
