### ISSUE TITLE
Build is broken on master

### ISSUE THREAD

**Issue by apbendi** [casey/ord#1603]
Fetched most recent master, ran `cargo build --release`, fails with the following errors:

```
error[E0658]: use of unstable library feature 'map_first_last'
   --> /home/usr/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.13.0/src/tree_store/page_store/cached_file.rs:257:50
    |
257 |                 if let Some((_, v)) = write_lock.pop_first() {
    |                                                  ^^^^^^^^^
    |
    = note: see issue #62924 <https://github.com/rust-lang/rust/issues/62924> for more information

error[E0658]: use of unstable library feature 'map_first_last'
   --> /home/usr/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.13.0/src/tree_store/page_store/cached_file.rs:319:58
    |
319 |                     if let Some((offset, buffer)) = lock.pop_first() {
    |                                                          ^^^^^^^^^
    |
    = note: see issue #62924 <https://github.com/rust-lang/rust/issues/62924> for more information
```

Running:

rustc 1.65.0 (897e37553 2022-11-02)
rustc 1.65.0 (897e37553 2022-11-02)

On Ubuntu 22.04

**Comment by raphjaph** [comment]
We're on the newest stable rustc (`rustc 1.67.0 (fc594f156 2023-01-24)`) because of our bleeding edge [database](https://github.com/cberner/redb).

Just do `rustup update`

**Comment by casey** [comment]
I think this fixes it. Please feel free to reopen if updating Rust doesn't work!

**Comment by random9brat** [comment]
rustup update doesnt work, says:

info: no updatable toolchains installed
info: cleaning up downloads & tmp directories

even tho rustc --version shows me rustc 1.61.0

any advice ?

**Comment by raphjaph** [comment]
What is the output of `rustup show`?

**Comment by random9brat** [comment]
Default host: armv7-unknown-linux-gnueabihf
rustup home:  /root/snap/rustup/common/rustup

no active toolchain

**Comment by raphjaph** [comment]
Maybe try `rustup default stable` to activate the stable toolchain. Otherwise reinstall or try looking at `rustup help`. I'm not at my computer at the moment so unfortunately can't look up the commands.

**Comment by random9brat** [comment]
So I manage to install it but still cant find nothing with ord -v (ord --version) within the system even tho I had this:

Compiling ord v0.4.2 (/ssd/ordinals/ord)
Finished dev [unoptimized + debuginfo] target(s) in 22m 19s

I had to install it manually with cargo build since I had this error when I tried to execute ./install.sh

 "install: error: Could not determine target from output of `uname -m`-`uname -s`, please use `--target`: armv7l-Linux"

**Comment by raphjaph** [comment]
When you compile with `cargo build --release` the executable is put in `./target/release/ord` you can copy it out and put it anywhere your shell can find it. Or you use `cargo install --path <PATH>` to directly install somewhere in your $PATH

**Comment by kalibox** [comment]
> When you compile with `cargo build --release` the executable is put in `./target/release/ord` you can copy it out and put it anywhere your shell can find it. Or you use `cargo install --path <PATH>` to directly install somewhere in your $PATH

Might be good to mention this in the build guide for folks compiling from git.
