### ISSUE TITLE
Having issue when running`RUST_LOG=info ord index` after laptop battery died in the middle of ord index syncing process. 

### ISSUE THREAD

**Issue by kahseng94** [casey/ord#1624]
keep getting this error `error: I/O error: failed to fill whole buffer` when trying to sync ord index.

**Comment by raphjaph** [comment]
Does it continue indexing or just immediately exit?

If you battery died in the middle of syncing the database might be corrupted/in an invalid state. So you might have to delete `index.redb` and start new unfortunately. You can find it on `Library/Application\ Support/ord/` on Mac or `/var/lib/ord` on Linux

**Comment by kahseng94** [comment]
This is the error msg `error: I/O error: failed to fill whole buffer`. "Start new" means reinstall `ord`, or do I need to redownload the whole bitcoin node?

**Comment by raphjaph** [comment]
Start new means deleting the `index.redb` file (our database) and rebuilding the `ord` database again. You can find that file in one of  paths mentioned above. You do not have to reinstall `ord` or Bitcoin Core. You can delete a file on the command line with `rm <FILENAME>`.

**Comment by kahseng94** [comment]
just finishing indexing the block. It works, thank you!
