### ISSUE TITLE
Question...is the @ordinalswallet on twitter your account

### ISSUE THREAD

**Issue by partnercloudsupport** [casey/ord#1639]
Hi Casey...is the @ordinalswallet on twitter your account. https://twitter.com/ordinalswallet.

Wanted to confirm. Thank you

**Comment by windsok** [comment]
This twitter has no association with the ordinals open source project

**Comment by partnercloudsupport** [comment]
@casey  Thanks for letting us know!

**Comment by nammaki** [comment]
Why are they sketchy? Their website looks like the nicest explorer out of what I see 🤔
