### ISSUE TITLE
.cookie file example

### ISSUE THREAD

**Issue by random9brat** [casey/ord#1656]
Heyoo,

I cant start btc node without specify rpcuser and rpcpassword so my node is not generating .cookie file which is used from ord to connect to bitcoin core. Any chance someone could navigate me how to fix this or give me an example of bitcoin .cookie file since I cant find one over the internet...

**Comment by random9brat** [comment]
the way of resolving this is to delete rpcuser and rpcpassword from bitcoin.conf, not just in datadir you are running but also in the /root/.bitcoin folder too (dont know why this had to be done, if someone can explain to me i would apprecaite it)...

**Comment by raphjaph** [comment]
https://github.com/bitcoin/bitcoin/tree/master/share/rpcauth
