### ISSUE TITLE
'ord' command not recognizing in shell 

### ISSUE THREAD

**Issue by richscenius** [casey/ord#1658]
tried to install using both source binaries and curl --proto '=https' --tlsv1.2 -fsLS https://ordinals.com/install.sh | bash -s. it says "ord already exists in /home/ubuntu/bin" but when i push "ord" in shell it says "command ord not found" ... is there a PATH edit i need to make?

**Comment by futuremihai** [comment]
Yes, set PATH to $PATH /home/[your username]/bin.

For me on AWS it's "set PATH $PATH /home/ubuntu/bin".

**Comment by junlt01** [comment]
Hi, 
i get the same issue while working on ORD 
after usin
<img width="798" alt="Screenshot 2023-02-12 at 13 06 15" src="https://user-images.githubusercontent.com/125176038/218295892-01c46f28-1159-4bef-b359-be1ec110c840.png">
g curl --proto '=https' --tlsv1.2 -fsLS https://ordinals.com/install.sh | bash -s and have ord in /home/ubuntu/bin 
the o
<img width="798" alt="Screenshot 2023-02-12 at 13 06 15" src="https://user-images.githubusercontent.com/125176038/218295865-e2d80f78-63b2-4ad8-8031-e64c5e9f7be2.png">
rd still not install properly 
Currently, im running it on AWS. After using "set PATH $PATH /home/ubuntu/bin" as above it show like this:
Any recommendation would be highly appreciated .

**Comment by raphjaph** [comment]
You have to update ubuntu to 22.04. See #1430
