### ISSUE TITLE
fee prepayment leads to stuck funds, when using no-limit option the reveal tx has negative fee

### ISSUE THREAD

**Issue by A60AB5450353F40E** [casey/ord#1673]
So I did a `./ord wallet inscribe --fee-rate 4.0 --no-limit` with a 2,588,256 byte file :)

The wallet made 2 outputs, as you can see here: https://mempool.space/tx/32c5b7732e7d7ef36ce80e74cf7359d7cf0692bf1dcb9704fb5bfbb679801d0c

My mistake was that fee rate was impossible because I didn't have enough balance so I guess it defaulted to 1sat/vb?

But why do you fund the commitment utxo with anything more than dust, wouldn't it be better to use a 2nd input to pay for the fee?

Also, the wallet seems to have generated the reveal TX such that the fee is negative, here's the reveal TX the ord wallet created: https://gist.githubusercontent.com/A60AB5450353F40E/51d4430af6881d827bdb71b8cde26b23/raw/a20f18dbe39e86eacb88be0aa471119160c49e05/inscrtiption1.md

Would be nice if there was a way to customize it:
- add an extra input to increase the fee
- reduce the output value

**Comment by A60AB5450353F40E** [comment]
Ok I figured out how to use the taproot pubkey path to reclaim the btc from the commitment UTXO, closing

**Comment by ittechguruuu** [comment]
> Ok I figured out how to use the taproot pubkey path to reclaim the btc from the commitment UTXO, closing


@casey any ETA on bump fee feature on ord wallet ? Using bitcoin ci to bump fee is risky... My transaction is stuck at 1sat/vbyte :(.

Did you fixed it? My inscribe stuck also with 1sat/vbyte :(. And no way to create new one because previous stuck?

**Comment by A60AB5450353F40E** [comment]
>My inscribe stuck also with 1sat/vbyte

Is your commitment TX mined? I figured out that I can spend it back into my wallet, you need to use `bitcoin-cli` and `createrawtransaction` function to manually create an input that spends the commitment UTXO. Then, you use the `signrawtransactionwithwallet` function to sign the input, and finally `sendrawtransaction` to broadcast it.

**Comment by elpro234** [comment]
@A60AB5450353F40E can you tell me please which specific commands I should run to solve the problem , I have the same issue.

**Comment by A60AB5450353F40E** [comment]
Sorry, I forgot exactly how I used them, don't have the node running anymore to check, having finished my business with the inscription I wanted to make :)

I think that you can specify from which address you will spend when using `createrawtransaction` and there you just specify the commitment TX output's address. Just follow the instructions from `bitcoin-cli help createrawtransaction`
