### ISSUE TITLE
When compiling from source, where is the binary?

### ISSUE THREAD

**Issue by carboncls** [casey/ord#1681]
I tried to build from source, and it ended with a success message:

```
Compiling ord v0.4.2 (/home/folder/ord)
Finished release [optimized] target(s) in 8m 46s
```
however, in /home/folder/ord, there was no `ord` binary. `whereis ord` also didn't found anything.

Ubuntu LTS 22.04.

**Comment by Psifour** [comment]
My output typically goes to the 'target' directory under the ord directory.

**Comment by donnlee** [comment]
target/release

**Comment by carboncls** [comment]
thanks. I needed to ./install.sh first.
