### ISSUE TITLE
Allowing file format .glb to be inscribed.

### ISSUE THREAD

**Issue by BLE77** [casey/ord#1683]
A GLB file (. glb), which stands for “GL Transmission Format Binary file”, is a standardized file format used to share 3D data.
This file format allows for 3D objects to be viewed with a web based viewer. I suggest < model viewer > if we do want the ordinal website itself to display these. If not then just having .glb assets that could be called by other ordinals would allow for that experience too! Would love to be able to inscribe them now though until that issue is solved.

**Comment by Psifour** [comment]
Resolved by #1666 

Issue created after resolving PR
@BLE77 please close or include additional work required.

**Comment by casey** [comment]
On my phone, but could someone follow up with an issue to create a .glb viewer? You can currently create .glb inscriptions, but not view them, which is not ideal.

**Comment by BLE77** [comment]
https://github.com/casey/ord/issues/1707
