### ISSUE TITLE
Optimize HTML inscriptions with brotli compression 

### ISSUE THREAD

**Issue by darbsllim** [casey/ord#1699]
One way to optimize usage of bitcoin blockspace by ordinals is to compress the data used by certain inscriptions in the witness data.

@casey suggested that the Brotli algorithm could be used to compress html data by up to 75%

https://en.wikipedia.org/wiki/Brotli

If someone wants to write this pull request and gets it merged, I'm willing to pay a bounty of 5,000,000 sats.

**Comment by huuep** [comment]
This is great. Combine this with https://github.com/casey/ord/discussions/1647 and we can really inscribe amazing generative NFTs on Bitcoin!

**Comment by casey** [comment]
I think this is a dupe, but it has a bounty. Right now, I think that I don't want to think too hard about bounties, since they feel like a potential headache. (Who was first? What counts?) For further discussion of bounties, I think a discussion or discord.gg/ordinals would be good! 🙏

**Comment by staccDOTsol** [comment]
@darbsllim can you elaborate what @casey means here in my 2nd attempt to have brotli merged:

https://github.com/ordinals/ord/pull/2231

I am unsure why rewriting the entire ord specification for a new field is necessary when we can just default to brotli everything and decode if it is expressed in the content-type; whereas I'm unsure how to rewrite ordinal http server to determine if a field is nonexistent in an ordinal that had been minted before this compression was instituted.

**Comment by casey** [comment]
Content type is not how compression is expressed, it's a separate header, the content-encoding header.

**Comment by jerryarmstrong** [comment]
thank you @casey I'm gonna take another crack at it, I need it for something else and it's easier than setting up our own ord explorer if it was accepted into the ord protocol. Any chance the bounty is still open?

**Comment by jerryarmstrong** [comment]
Mind you I did use content-encoding? 

```
let content_type = Media::content_type_for_path(path)?;
      Ok(Self {
        body: Some(encoded_body),
        content_type: Some(content_type.into()),
        content_encoding: Some("br".into()) 
      })
    } else {
      let content_type = Media::content_type_for_path(path)?;
      Ok(Self {
        body: Some(body),
        content_type: Some(content_type.into()),
        content_encoding: None
      })
    }```
