### ISSUE TITLE
error: Table 'STATISTIC_TO_COUNT' does not exist

### ISSUE THREAD

**Issue by paulscode** [casey/ord#1710]
After upgrading from 0.4.2 to 0.5.0, the ord "**wallet outputs**" command on my system fails with the following output:

`error: Table 'STATISTIC_TO_COUNT' does not exist
`

Note that this command did work properly prior to the upgrade

**Details**

Today I pulled the latest ord 0.5.0, to upgrade from version 0.4.2 (which I had also originally built from source).  For reference, the process I followed to perform the update was:

```
git fetch
git checkout 0.5.0
cargo clean
cargo build --release
```

**Additional Environment Details**

Versions:

```
ord             0.5.0   (compiled from source, tag 0.5.0)
Rust            1.67.1
Bitcoin Core    24.0.1  (snap install)
```

System:

```
Hardware       Raspberry Pi 4B        (2GB RAM model)
OS             Raspbian 11 "Bullseye" (Linux, Debian-like)
Architecture   armv7l                 (32 bit)
```

--UPDATE--
I see also that I get the same error for the "**wallet balance**" and "**wallet inscribe**" commands, so it isn't specific to wallet outputs.

**Comment by paulscode** [comment]
I figured out the problem.  I hadn't paid attention to the 0.5.0 changelog, where I should have seen that there was a breaking change redb update.

Deleting ~/.local/share/ord/index.redb appears to have fixed the problem.  Closing this issue.

**Comment by casey** [comment]
Things like this should go to GitHub discussions or discord.gg/ordinals 🙏

**Comment by casey** [comment]
Issues are for bug reports and specific feature requests only

**Comment by paulscode** [comment]
Thanks, will keep that in mind.  Note that I originally thought it was a bug with 0.5.0, and so I opened this issue to report it ;)
