### ISSUE TITLE
Immutability / Royalties / Collections / Scripts - some thoughts

### ISSUE THREAD

**Issue by Aervue** [casey/ord#1714]
Coming from Cardano Development I can see many similarities in various aspects of the minting process and the standard that providers must follow for everything to work. 

I'll explain how the process is there.

From a wallet you are able to generate a policy id (it's tied to your wallet there internally). This id is the identifier of an entire collection. Furthermore this id contains a script:

```json
{
  "type": "all",
  "scripts": [
    {
      "type": "before",
      "slot": 38082894
    },
    {
      "type": "sig",
      "keyHash": "c74140d3c5946dc5fdb4cf97f0c9fed6f138969005d81d3ba12b714c"
    }
  ]
}
```

The section "before": "38082894" determines until what block you can mint or make changes to this collection.

If you are the owner of the collection you can mint and make changes to it before that block height is reached. Minting metadata looks like this for 2 assets at the same time:

```json
{
  "721": {
   "d5e6bf0500378d4f0da4e8dde6becec7621cd8cbf5cbb9b87013d4cc": {
      "SpaceBud1020": {
         "arweaveId": "hIBgOo6-9PDBNBJID4-9hjcnyc9zVeuhU7tzr4f7MWI",
         "image": "ipfs://Qmc4mgJcsJ2oCkpda4UpuYc9JHiPFUtUNLC9rg41uGRBEw",
         "name": "SpaceBud #1020",
         "traits": [
          "Star Suit",
          "Chestplate",
          "Belt",
          "Covered Helmet",
          "SPO"
        ],
         "type": "Ape"
      },
      "SpaceBud1043": {
         "arweaveId": "x6A-m2OrN3vzGyxMhRNPXBkkRizZIMT_myxwc9vTIoQ",
         "image": "ipfs://QmUuu6kFK4omAKhf77vVRNrZcA3LNDjRmjAaAZCbAVuXSj",
         "name": "SpaceBud #1043",
         "traits": [
          "Belt",
          "Wool Boots",
          "SPO"
        ],
         "type": "Tiger"
      }
    }
  }
}
```

d5e6bf0500378d4f0da4e8dde6becec7621cd8cbf5cbb9b87013d4cc = the policy id, unique identifier to determine authenticity
SpaceBud1020 = internal name of the first asset, this could be an ordinal identifier
SpaceBud1043 = internal name of the second asset, ...

To update it you would have to just write the metadata again as long as the script has not expired.

The only thing that needs to be immutable is the policy id script.

Like on Cardano, it would be the responsability of the providers to query the chain for the latest authentic data that respects the script expiration. Why don't we do that here? We can include royalties and such in the immutable creation script, and only the creator is allowed to do such an update. While on Cardano there are some parts built on the main chain there shoulld be no problem to do everything here.

We would just need to figure out the policy id how to best implement it. One ideea would be to create and burn a satoshi for initialization of the immutable script and use that satoshi as the identifier for the collection and referencing it in the followings inscriptions?

There are various benefits in having updates, like fixing mistakes in metadata, long term collection minting, update the character stats of a game NFT.

Thoughts?

**Comment by casey** [comment]
Please open an issue with a specific feature request, and I can respond to it. These are great starts:

- fixing mistakes in metadata
- long term collection minting
- update the character stats of a game NFT

As a general comment: mutability is a boondoggle.

**Comment by casey** [comment]
Also, I'm not interested in trying understand the details of altcoins, so they are off topic. You are free to propose a specific feature that is present in an altcoin, or a specific PR implementing something that is implemented in an altcoin.

If you want to have a discussion, like "this is how it works in Ethereum", please open a discussion. I'll be more lenient on Ethereum, because it's popular, but worthless rube goldberg machines like cardano are basically unworthy of consideration.
