### ISSUE TITLE
Cannot send without also sending inscription [ID]

### ISSUE THREAD

**Issue by 0xridey** [casey/ord#1735]
I am trying to move some of my inscriptions and somehow, there's an issue that is not letting me to, what's the safest way to send them without losing any.

```
error: cannot send f9aeaf39fca3597d57f4308355591bc437032ce5562efae07d62d25a842ccc5d:0:0 without also sending inscription 311ecd1126d0e6f754ce4d75ebf1b950401af51bd62041f4f8844d198c322cbci0 at f9aeaf39fca3597d57f4308355591bc437032ce5562efae07d62d25a842ccc5d
error: cannot send f9aeaf39fca3597d57f4308355591bc437032ce5562efae07d62d25a842ccc5d:0:20000 without also sending inscription c8259f192aa2656a89a89e91f6779dc217ce0522abd07b699c96d82c393ac4f6i0 at f9aeaf39fca3597d57f4308355591bc437032ce5562efae07d62d25a842ccc5d
error: cannot send f9aeaf39fca3597d57f4308355591bc437032ce5562efae07d62d25a842ccc5d:0:30000 without also sending inscription c8259f192aa2656a89a89e91f6779dc217ce0522abd07b699c96d82c393ac4f6i0 at f9aeaf39fca3597d57f4308355591bc437032ce5562efae07d62d25a842ccc5d
error: cannot send f9aeaf39fca3597d57f4308355591bc437032ce5562efae07d62d25a842ccc5d:0:10000 without also sending inscription c8259f192aa2656a89a89e91f6779dc217ce0522abd07b699c96d82c393ac4f6i0 at f9aeaf39fca3597d57f4308355591bc437032ce5562efae07d62d25a842ccc5d
error: cannot send 0f04f454a52f69b78aabfd156b39cafac383c5ab47bc525f8f399197dd392089:1:184031 without also sending inscription 323a23e4d7b97e72bc32a60565f302c84bf7750e3ac559cb8635baf1a7f3ffeei0 at 0f04f454a52f69b78aabfd156b39cafac383c5ab47bc525f8f399197dd392089
error: cannot send 0f04f454a52f69b78aabfd156b39cafac383c5ab47bc525f8f399197dd392089:1:194031 without also sending inscription 323a23e4d7b97e72bc32a60565f302c84bf7750e3ac559cb8635baf1a7f3ffeei0 at 0f04f454a52f69b78aabfd156b39cafac383c5ab47bc525f8f399197dd392089
error: cannot send 0f04f454a52f69b78aabfd156b39cafac383c5ab47bc525f8f399197dd392089:1:144031 without also sending inscription 4dc75d4b42cf7e620daa4d895483295ba9cc1ff3aee298a3539fbbad1b4d084ei0 at 0f04f454a52f69b78aabfd156b39cafac383c5ab47bc525f8f399197dd392089
error: cannot send 0f04f454a52f69b78aabfd156b39cafac383c5ab47bc525f8f399197dd392089:1:164031 without also sending inscription 323a23e4d7b97e72bc32a60565f302c84bf7750e3ac559cb8635baf1a7f3ffeei0 at 0f04f454a52f69b78aabfd156b39cafac383c5ab47bc525f8f399197dd392089
error: cannot send 0f04f454a52f69b78aabfd156b39cafac383c5ab47bc525f8f399197dd392089:1:174031 without also sending inscription 323a23e4d7b97e72bc32a60565f302c84bf7750e3ac559cb8635baf1a7f3ffeei0 at 0f04f454a52f69b78aabfd156b39cafac383c5ab47bc525f8f399197dd392089
```

**Comment by raphjaph** [comment]
At the moment we have very strict rules so no inscriptions get lost. You will have to send each inscription separately by specifying the inscription ID  like so: `ord wallet send <ADDRESS> <INSCRIPTION_ID>`

**Comment by 0xridey** [comment]
@raphjaph that appears when I try to send an inscription, one line represents the result for a command.

**Comment by raphjaph** [comment]
It seems you like you have multiple inscriptions per utxo. Did you use `bitcoin-cli` at some point?

Could you post the exact command you used with the output for that command beneath it?

**Comment by 0xridey** [comment]
I haven't used bitcoin-cli while inscripting these. I think we have misunderstanding, apologize for the misexplanation.

If I type as usual for the following inscription `311ecd1126d0e6f754ce4d75ebf1b950401af51bd62041f4f8844d198c322cbci0` to send it to another wallet.

`ord wallet send --fee-rate 20 <btc-address> <inscription>`

I get the following issue:

```
error: cannot send f9aeaf39fca3597d57f4308355591bc437032ce5562efae07d62d25a842ccc5d:0:0 without also sending inscription 311ecd1126d0e6f754ce4d75ebf1b950401af51bd62041f4f8844d198c322cbci0 at f9aeaf39fca3597d57f4308355591bc437032ce5562efae07d62d25a842ccc5d
```

I've written all the errors, because I thought it could lead to find the issue.

**Comment by raphjaph** [comment]
No problem! Providing all the output is definitely a good idea!

This seems be related to #1429. We added fix so that situation can't happen in #1459 but for you it has already happened so it doesn't fix your situation unfortunately. We are working on providing the ability to disaggregate inscriptions in the same UTXO. For now you will have to hold on to your inscriptions.

**Comment by dvncan** [comment]
I have also received this error. I am running a new index on version 0.5.0

I ran the same command as the user above.

`
error: cannot send 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:20000 without also sending inscription 18e09100b38a7174bdfea4a1c505a16bcdd4af2b4dbed3a1b7cf1cf7ad82dfdei0 at 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:0
error: cannot send 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:30000 without also sending inscription 18e09100b38a7174bdfea4a1c505a16bcdd4af2b4dbed3a1b7cf1cf7ad82dfdei0 at 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:0
error: cannot send 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:40000 without also sending inscription 18e09100b38a7174bdfea4a1c505a16bcdd4af2b4dbed3a1b7cf1cf7ad82dfdei0 at 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:0
error: cannot send 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:50000 without also sending inscription 18e09100b38a7174bdfea4a1c505a16bcdd4af2b4dbed3a1b7cf1cf7ad82dfdei0 at 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:0
error: cannot send 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:60000 without also sending inscription 18e09100b38a7174bdfea4a1c505a16bcdd4af2b4dbed3a1b7cf1cf7ad82dfdei0 at 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:0
error: cannot send 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:70000 without also sending inscription 18e09100b38a7174bdfea4a1c505a16bcdd4af2b4dbed3a1b7cf1cf7ad82dfdei0 at 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:0
error: cannot send 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:80000 without also sending inscription 18e09100b38a7174bdfea4a1c505a16bcdd4af2b4dbed3a1b7cf1cf7ad82dfdei0 at 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:0
error: cannot send 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:90000 without also sending inscription 18e09100b38a7174bdfea4a1c505a16bcdd4af2b4dbed3a1b7cf1cf7ad82dfdei0 at 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:0
error: cannot send 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:100000 without also sending inscription 18e09100b38a7174bdfea4a1c505a16bcdd4af2b4dbed3a1b7cf1cf7ad82dfdei0 at 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:0
error: cannot send 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:110000 without also sending inscription 18e09100b38a7174bdfea4a1c505a16bcdd4af2b4dbed3a1b7cf1cf7ad82dfdei0 at 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:0
error: cannot send 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:133950 without also sending inscription 18e09100b38a7174bdfea4a1c505a16bcdd4af2b4dbed3a1b7cf1cf7ad82dfdei0 at 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:0
error: cannot send 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:143950 without also sending inscription 18e09100b38a7174bdfea4a1c505a16bcdd4af2b4dbed3a1b7cf1cf7ad82dfdei0 at 2e622de1bf5d385fcce9b790e19cfe378e99e5d1f23408fe30509ca3b5f78d52:0:0
`

**Comment by pdm1230** [comment]
I encouter the same problem, have 4 inscriptions in the same output.
How to split them? 
Thanks.

**Comment by 0xridey** [comment]
A guy called `Greg#0913` on ordinals discord helped me with it, I was able to separate them without any problem via bitcoin core.

Do not forget to tip him, amazing guy ^^

**Comment by gmart7t2** [comment]
> A guy called `Greg#0913` on ordinals discord helped me with it, I was able to separate them without any problem via bitcoin core.
> 
> Do not forget to tip him, amazing guy ^^

Hey that's me. Greg#0913 on discord. DM me and I'll help you out
