### ISSUE TITLE
os error 10053

### ISSUE THREAD

**Issue by somenormalguy7** [casey/ord#1746]
![image](https://user-images.githubusercontent.com/52010198/218965147-aa1a1654-8583-4fd9-af79-73d298e1c805.png)

how can I fix it?

**Comment by belovie** [comment]
Was there an answer? I am having the same issue.

**Comment by 0xRabbidfly** [comment]
i'm getting this error now that i have upgraded to 0.8 

i'm sure it's a pretty simple fix - my anti-virus is OFF and my firewall is OFF, so i shouldn't be getting RPC connection errors
