### ISSUE TITLE
Make `--fee-rate` a mandatory argument for `wallet send`

### ISSUE THREAD

**Issue by veryordinally** [casey/ord#1747]
Per suggestion from RarePepeMaximalist.

Lots of transaction getting stuck in mempool at  default 1sat/vByte, which we may never see clear again.

I think it'd be better to make `--fee-rate` a required parameter. Ord users will have to learn about fee market anyways.

**Comment by raphjaph** [comment]
Merging #1755 which will make `--fee-rate` mandatory. For this issue to be closed we need it for `wallet inscribe` as well.

**Comment by casey** [comment]
Partially fixed by #1755. Closing in favor of #1432, which has details on a full fix.

**Comment by veryordinally** [comment]
Created follow up issue #1767 for the `wallet inscribe` part.
