### ISSUE TITLE
How can I use an inscription inside another inscription?

### ISSUE THREAD

**Issue by chuiso-on-chain** [casey/ord#1757]
Hi!! is there any documentation about adding inscriptions inside other inscriptions? It is mention it in the doc:

> _The inscription content model is that of the web. An inscription consists of a content type, also known as a MIME type, and the content itself, which is a byte string. This allows inscription content to be returned from a web server, and for creating HTML inscriptions that use and remix the content of other inscriptions._

For example, I inscribe some PNG images that are resources for a videogame, and then I inscribe an HTML game that uses this inscriptions as resources

But how I can do it? How embed inscriptions inside another inscription? is there any example or documentation?

Regards.

**Comment by octal-crypto** [comment]
On roadmap: https://github.com/casey/ord/issues/1082

**Comment by RarePepeMaximalist** [comment]
As @octal-crypto points out, this is a future planned feature. Feel free to start a [discussion](https://github.com/casey/ord/discussions) about how you would like to use this future feature. Also feel free to contribute any implementation ideas on #1082
