### ISSUE TITLE
ord reporting wallet balance zero, bitcoind shows correct amount. 

### ISSUE THREAD

**Issue by m5k** [casey/ord#1758]
I sent funds from Kraken to the ord generated receiving address "bc1pz6xxxxxxxxx". The fund are there (22 confirmations). However the ord wallet balance returns zero. ord wallet outputs returns nothing. Is there something else I need to do? This is a fresh setup, all blocks indexed, node 100% synced to latest block. No inscriptions or other transactions have been sent/received. 

Results of ord wallet balance:
{
  "cardinal": 0
}

Results of ord wallet outputs:
[]

Results of bitcoin-cli getbalance: 
0.00047211

Thank you.

**Comment by m5k** [comment]
./ord info
{
  "blocks_indexed": 776712,
  "branch_pages": 60423,
  "fragmented_bytes": 5278354120,
  "index_file_size": 32253648896,
  "index_path": "/home/rpc/.local/share/ord/index.redb",
  "leaf_pages": 2745776,
  "metadata_bytes": 177333260,
  "outputs_traversed": 0,
  "page_size": 4096,
  "sat_ranges": 0,
  "stored_bytes": 6091329836,
  "transactions": [
    {
      "starting_block_count": 0,
      "starting_timestamp": 1676424296182
    },
    {
      "starting_block_count": 5000,
      "starting_timestamp": 1676424299887
    },
    {
      "starting_block_count": 10000,
      "starting_timestamp": 1676424303083
    },
    {
      "starting_block_count": 15000,
      "starting_timestamp": 1676424306477
    },
    {
      "starting_block_count": 20000,
      "starting_timestamp": 1676424309832
    },
    {
      "starting_block_count": 25000,
      "starting_timestamp": 1676424313001
    },
    {
      "starting_block_count": 30000,
      "starting_timestamp": 1676424316061
    },
    {
      "starting_block_count": 35000,
      "starting_timestamp": 1676424319188
    },
    {
      "starting_block_count": 40000,
      "starting_timestamp": 1676424322273
    },
    {
      "starting_block_count": 45000,
      "starting_timestamp": 1676424325773
    },
    {
      "starting_block_count": 50000,
      "starting_timestamp": 1676424328953
    },
    {
      "starting_block_count": 55000,
      "starting_timestamp": 1676424332705
    },
    {
      "starting_block_count": 60000,
      "starting_timestamp": 1676424335845
    },
    {
      "starting_block_count": 65000,
      "starting_timestamp": 1676424339124
    },
    {
      "starting_block_count": 70000,
      "starting_timestamp": 1676424345003
    },
    {
      "starting_block_count": 75000,
      "starting_timestamp": 1676424349509
    },
    {
      "starting_block_count": 80000,
      "starting_timestamp": 1676424353470
    },
    {
      "starting_block_count": 85000,
      "starting_timestamp": 1676424358106
    },
    {
      "starting_block_count": 90000,
      "starting_timestamp": 1676424362069
    },
    {
      "starting_block_count": 95000,
      "starting_timestamp": 1676424371569
    },
    {
      "starting_block_count": 100000,
      "starting_timestamp": 1676424375892
    },
    {
      "starting_block_count": 105000,
      "starting_timestamp": 1676424384379
    },
    {
      "starting_block_count": 110000,
      "starting_timestamp": 1676424400873
    },
    {
      "starting_block_count": 115000,
      "starting_timestamp": 1676424427759
    },
    {
      "starting_block_count": 120000,
      "starting_timestamp": 1676424461041
    },
    {
      "starting_block_count": 125000,
      "starting_timestamp": 1676424523128
    },
    {
      "starting_block_count": 130000,
      "starting_timestamp": 1676424631185
    },
    {
      "starting_block_count": 135000,
      "starting_timestamp": 1676424760947
    },
    {
      "starting_block_count": 140000,
      "starting_timestamp": 1676424891193
    },
    {
      "starting_block_count": 145000,
      "starting_timestamp": 1676425020684
    },
    {
      "starting_block_count": 150000,
      "starting_timestamp": 1676425150932
    },
    {
      "starting_block_count": 155000,
      "starting_timestamp": 1676425278606
    },
    {
      "starting_block_count": 160000,
      "starting_timestamp": 1676425399567
    },
    {
      "starting_block_count": 165000,
      "starting_timestamp": 1676425525797
    },
    {
      "starting_block_count": 170000,
      "starting_timestamp": 1676425656394
    },
    {
      "starting_block_count": 175000,
      "starting_timestamp": 1676425779096
    },
    {
      "starting_block_count": 180000,
      "starting_timestamp": 1676425910493
    },
    {
      "starting_block_count": 185000,
      "starting_timestamp": 1676426018950
    },
    {
      "starting_block_count": 190000,
      "starting_timestamp": 1676426131412
    },
    {
      "starting_block_count": 195000,
      "starting_timestamp": 1676426249044
    },
    {
      "starting_block_count": 200000,
      "starting_timestamp": 1676426365138
    },
    {
      "starting_block_count": 205000,
      "starting_timestamp": 1676426477215
    },
    {
      "starting_block_count": 210000,
      "starting_timestamp": 1676426591733
    },
    {
      "starting_block_count": 215000,
      "starting_timestamp": 1676426714970
    },
    {
      "starting_block_count": 220000,
      "starting_timestamp": 1676426845424
    },
    {
      "starting_block_count": 225000,
      "starting_timestamp": 1676426976252
    },
    {
      "starting_block_count": 230000,
      "starting_timestamp": 1676427104500
    },
    {
      "starting_block_count": 235000,
      "starting_timestamp": 1676427238658
    },
    {
      "starting_block_count": 240000,
      "starting_timestamp": 1676427376015
    },
    {
      "starting_block_count": 245000,
      "starting_timestamp": 1676427499936
    },
    {
      "starting_block_count": 250000,
      "starting_timestamp": 1676427620768
    },
    {
      "starting_block_count": 255000,
      "starting_timestamp": 1676427754807
    },
    {
      "starting_block_count": 260000,
      "starting_timestamp": 1676427884959
    },
    {
      "starting_block_count": 265000,
      "starting_timestamp": 1676428012691
    },
    {
      "starting_block_count": 270000,
      "starting_timestamp": 1676428147676
    },
    {
      "starting_block_count": 275000,
      "starting_timestamp": 1676428305045
    },
    {
      "starting_block_count": 280000,
      "starting_timestamp": 1676428457751
    },
    {
      "starting_block_count": 285000,
      "starting_timestamp": 1676428609040
    },
    {
      "starting_block_count": 290000,
      "starting_timestamp": 1676428778387
    },
    {
      "starting_block_count": 295000,
      "starting_timestamp": 1676428947537
    },
    {
      "starting_block_count": 300000,
      "starting_timestamp": 1676429122563
    },
    {
      "starting_block_count": 305000,
      "starting_timestamp": 1676429296836
    },
    {
      "starting_block_count": 310000,
      "starting_timestamp": 1676429467389
    },
    {
      "starting_block_count": 315000,
      "starting_timestamp": 1676429647993
    },
    {
      "starting_block_count": 320000,
      "starting_timestamp": 1676429832456
    },
    {
      "starting_block_count": 325000,
      "starting_timestamp": 1676430025091
    },
    {
      "starting_block_count": 330000,
      "starting_timestamp": 1676430229946
    },
    {
      "starting_block_count": 335000,
      "starting_timestamp": 1676430452434
    },
    {
      "starting_block_count": 340000,
      "starting_timestamp": 1676430668886
    },
    {
      "starting_block_count": 345000,
      "starting_timestamp": 1676430891485
    },
    {
      "starting_block_count": 350000,
      "starting_timestamp": 1676431119342
    },
    {
      "starting_block_count": 355000,
      "starting_timestamp": 1676431356980
    },
    {
      "starting_block_count": 360000,
      "starting_timestamp": 1676431600065
    },
    {
      "starting_block_count": 365000,
      "starting_timestamp": 1676431900254
    },
    {
      "starting_block_count": 370000,
      "starting_timestamp": 1676432244698
    },
    {
      "starting_block_count": 375000,
      "starting_timestamp": 1676432519616
    },
    {
      "starting_block_count": 380000,
      "starting_timestamp": 1676432794507
    },
    {
      "starting_block_count": 385000,
      "starting_timestamp": 1676433093197
    },
    {
      "starting_block_count": 390000,
      "starting_timestamp": 1676433423394
    },
    {
      "starting_block_count": 395000,
      "starting_timestamp": 1676433765497
    },
    {
      "starting_block_count": 400000,
      "starting_timestamp": 1676434141120
    },
    {
      "starting_block_count": 405000,
      "starting_timestamp": 1676434516200
    },
    {
      "starting_block_count": 410000,
      "starting_timestamp": 1676434895965
    },
    {
      "starting_block_count": 415000,
      "starting_timestamp": 1676435297193
    },
    {
      "starting_block_count": 420000,
      "starting_timestamp": 1676435703530
    },
    {
      "starting_block_count": 425000,
      "starting_timestamp": 1676436115939
    },
    {
      "starting_block_count": 430000,
      "starting_timestamp": 1676436517097
    },
    {
      "starting_block_count": 435000,
      "starting_timestamp": 1676436925513
    },
    {
      "starting_block_count": 440000,
      "starting_timestamp": 1676437367192
    },
    {
      "starting_block_count": 445000,
      "starting_timestamp": 1676437815453
    },
    {
      "starting_block_count": 450000,
      "starting_timestamp": 1676438250413
    },
    {
      "starting_block_count": 455000,
      "starting_timestamp": 1676438713568
    },
    {
      "starting_block_count": 460000,
      "starting_timestamp": 1676439190338
    },
    {
      "starting_block_count": 465000,
      "starting_timestamp": 1676439674211
    },
    {
      "starting_block_count": 470000,
      "starting_timestamp": 1676440152592
    },
    {
      "starting_block_count": 475000,
      "starting_timestamp": 1676440632259
    },
    {
      "starting_block_count": 480000,
      "starting_timestamp": 1676441084443
    },
    {
      "starting_block_count": 485000,
      "starting_timestamp": 1676441568633
    },
    {
      "starting_block_count": 490000,
      "starting_timestamp": 1676442028468
    },
    {
      "starting_block_count": 495000,
      "starting_timestamp": 1676442559981
    },
    {
      "starting_block_count": 500000,
      "starting_timestamp": 1676443231081
    },
    {
      "starting_block_count": 505000,
      "starting_timestamp": 1676443803993
    },
    {
      "starting_block_count": 510000,
      "starting_timestamp": 1676444445584
    },
    {
      "starting_block_count": 515000,
      "starting_timestamp": 1676444961268
    },
    {
      "starting_block_count": 520000,
      "starting_timestamp": 1676445457338
    },
    {
      "starting_block_count": 525000,
      "starting_timestamp": 1676445978684
    },
    {
      "starting_block_count": 530000,
      "starting_timestamp": 1676446463892
    },
    {
      "starting_block_count": 535000,
      "starting_timestamp": 1676446939107
    },
    {
      "starting_block_count": 540000,
      "starting_timestamp": 1676447379927
    },
    {
      "starting_block_count": 545000,
      "starting_timestamp": 1676447855537
    },
    {
      "starting_block_count": 550000,
      "starting_timestamp": 1676448432222
    },
    {
      "starting_block_count": 555000,
      "starting_timestamp": 1676449048643
    },
    {
      "starting_block_count": 560000,
      "starting_timestamp": 1676449709826
    },
    {
      "starting_block_count": 565000,
      "starting_timestamp": 1676450336934
    },
    {
      "starting_block_count": 570000,
      "starting_timestamp": 1676450960948
    },
    {
      "starting_block_count": 575000,
      "starting_timestamp": 1676451700038
    },
    {
      "starting_block_count": 580000,
      "starting_timestamp": 1676452415874
    },
    {
      "starting_block_count": 585000,
      "starting_timestamp": 1676453105474
    },
    {
      "starting_block_count": 590000,
      "starting_timestamp": 1676453783612
    },
    {
      "starting_block_count": 595000,
      "starting_timestamp": 1676454505889
    },
    {
      "starting_block_count": 600000,
      "starting_timestamp": 1676455243754
    },
    {
      "starting_block_count": 605000,
      "starting_timestamp": 1676456012100
    },
    {
      "starting_block_count": 610000,
      "starting_timestamp": 1676456756223
    },
    {
      "starting_block_count": 615000,
      "starting_timestamp": 1676457502054
    },
    {
      "starting_block_count": 620000,
      "starting_timestamp": 1676458324351
    },
    {
      "starting_block_count": 625000,
      "starting_timestamp": 1676459236874
    },
    {
      "starting_block_count": 630000,
      "starting_timestamp": 1676460116626
    },
    {
      "starting_block_count": 635000,
      "starting_timestamp": 1676460971362
    },
    {
      "starting_block_count": 640000,
      "starting_timestamp": 1676461843670
    },
    {
      "starting_block_count": 645000,
      "starting_timestamp": 1676462835141
    },
    {
      "starting_block_count": 650000,
      "starting_timestamp": 1676463842025
    },
    {
      "starting_block_count": 655000,
      "starting_timestamp": 1676464778812
    },
    {
      "starting_block_count": 660000,
      "starting_timestamp": 1676465670047
    },
    {
      "starting_block_count": 665000,
      "starting_timestamp": 1676466693599
    },
    {
      "starting_block_count": 670000,
      "starting_timestamp": 1676467797267
    },
    {
      "starting_block_count": 675000,
      "starting_timestamp": 1676468810958
    },
    {
      "starting_block_count": 680000,
      "starting_timestamp": 1676469874414
    },
    {
      "starting_block_count": 685000,
      "starting_timestamp": 1676470876010
    },
    {
      "starting_block_count": 690000,
      "starting_timestamp": 1676471929609
    },
    {
      "starting_block_count": 695000,
      "starting_timestamp": 1676472803397
    },
    {
      "starting_block_count": 700000,
      "starting_timestamp": 1676473772546
    },
    {
      "starting_block_count": 705000,
      "starting_timestamp": 1676474695063
    },
    {
      "starting_block_count": 710000,
      "starting_timestamp": 1676475729111
    },
    {
      "starting_block_count": 715000,
      "starting_timestamp": 1676476897944
    },
    {
      "starting_block_count": 720000,
      "starting_timestamp": 1676477942915
    },
    {
      "starting_block_count": 725000,
      "starting_timestamp": 1676479031640
    },
    {
      "starting_block_count": 730000,
      "starting_timestamp": 1676480021152
    },
    {
      "starting_block_count": 735000,
      "starting_timestamp": 1676481061160
    },
    {
      "starting_block_count": 740000,
      "starting_timestamp": 1676482090382
    },
    {
      "starting_block_count": 745000,
      "starting_timestamp": 1676483147895
    },
    {
      "starting_block_count": 750000,
      "starting_timestamp": 1676484102377
    },
    {
      "starting_block_count": 755000,
      "starting_timestamp": 1676485038016
    },
    {
      "starting_block_count": 760000,
      "starting_timestamp": 1676485992176
    },
    {
      "starting_block_count": 765000,
      "starting_timestamp": 1676486998803
    },
    {
      "starting_block_count": 770000,
      "starting_timestamp": 1676488009499
    },
    {
      "starting_block_count": 775000,
      "starting_timestamp": 1676489477005
    },
    {
      "starting_block_count": 776699,
      "starting_timestamp": 1676490231668
    },
    {
      "starting_block_count": 776700,
      "starting_timestamp": 1676490402451
    },
    {
      "starting_block_count": 776701,
      "starting_timestamp": 1676490676557
    },
    {
      "starting_block_count": 776702,
      "starting_timestamp": 1676490943795
    },
    {
      "starting_block_count": 776705,
      "starting_timestamp": 1676491395941
    },
    {
      "starting_block_count": 776706,
      "starting_timestamp": 1676492150015
    },
    {
      "starting_block_count": 776707,
      "starting_timestamp": 1676492623475
    },
    {
      "starting_block_count": 776708,
      "starting_timestamp": 1676492752338
    },
    {
      "starting_block_count": 776711,
      "starting_timestamp": 1676493230877
    }
  ],
  "tree_height": 6,
  "utxos_indexed": 0
}

**Comment by m5k** [comment]
I sent 2nd amount of BTC to the wallet, a higher value. It showed nearly immediately with 1 confirmation. 

Seems the original transaction is still not showing. 

ord wallet balance
{
  "cardinal": 109000
}

Which is missing the original tx outputs. 

Perhaps there is something restricting such a low balance (0.00047211) from showing?

**Comment by Psifour** [comment]
Can you provide the TX of 47211 sats? While it is unlikely it is possible that range includes an inscription that someone mistakenly had sent to Kraken. If so it wouldn't count towards the balance shown in `ord wallet balance`. Alternately you can verify this yourself with `ord wallet inscriptions`

**Comment by m5k** [comment]
This has been resolved. Thank you for responding though.

**Comment by ordinalism** [comment]
@m5k How did you solve it? I am still facing the same issue? could you please explain
