### ISSUE TITLE
Dockerizing Ord wallet

### ISSUE THREAD

**Issue by dnilosek** [casey/ord#1764]
# Dockerizing Ord wallet

It could be useful for developers to be able to set up the ord wallet using a containerization approach. This would lower the barrier for those in a windows-based environment, but also if it was formally supported by the repo it could be published to places like docker.io where people could use it.

Realisitcally you would still need some interface to the docker container, if thats done through a simple http API and a localhost web interface or something like that. That would lower the barrier for entry for many.

**Comment by 0xBahamoot** [comment]
we use this for our internal ord server, maybe you can edit it to fit for windows-based environment?

```FROM ubuntu:latest
EXPOSE 8080
RUN #apk add tar --no-cache

WORKDIR /ordinals
ADD https://github.com/casey/ord/releases/download/0.5.0/ord-0.5.0-x86_64-unknown-linux-gnu.tar.gz /ordinals/ord.tar.gz
RUN tar -zxvf ord.tar.gz

RUN chmod +x /ordinals/ord
RUN ls -la
ENV RUST_LOG=debug

ENTRYPOINT ["/ordinals/ord", "--data-dir", "/ordinals/index-data", "--cookie-file", ".cookie", "server", "--http-port", "8080"]

**Comment by Magicking** [comment]
Adding another repository to the list that embed ord+bitcoin core(soon) and btcd(current) https://github.com/Magicking/ord-docker
