### ISSUE TITLE
Recovering Sparrow in Ord Extension 

### ISSUE THREAD

**Issue by christiankarakatsanis** [casey/ord#1773]
I am trying to recover my Sparrow wallet in the Ord Wallet extension on PC. I've tried the following command:

>ord wallet restore "Seed Phrase"

This returns me the following error:

"error: failed to connect to Bitcoin Core RPC at 127.0.0.1:8332/wallet/ord using cookie file C:\Users\catch\AppData\Roaming\Bitcoin\.cookie
because: I/O error: The system cannot find the file specified. (os error 2)"

I then tried adding the cookie file with the following command since it said it could not find the specified file:

>ord --cookie-file "Cookie File Path" wallet restore

That gave me the following error:

"error: JSON-RPC error: RPC error response: RpcError { code: -4, message: "Wallet file verification failed. Failed to create database path 'D:\\bitcoin-24.0.1\\Bitcoin\\ord'. Database already exists.", data: None }"

I have tried putting the entire seed phrase in one set of quotations and separating each word with quotations and neither have worked. Has anyone successfully recovered their Sparrow wallet in Ord?

**Comment by RarePepeMaximalist** [comment]
From the error message it sounds like you have already created a default wallet named `ord`.

You can import your wallet from sparrow using a different name by using the `--wallet` parameter

someone wrote some instructions for this here https://gist.github.com/windsok/5b53a1ced6ef3eddbde260337de28980#importing-into-ord-wallet

**Comment by RarePepeMaximalist** [comment]
@christiankarakatsanis closing this issue as I assume you were able to fix the issue by giving the wallet a new name.

Feel free to reopen if this is not the case
