### ISSUE TITLE
Running ord on a machine separate to BTC node

### ISSUE THREAD

**Issue by kalibox** [casey/ord#1793]
Hi, due to my current setup, I must use `ord` installed on a separate machine and connect to it via RPC. Is there an easy way of telling `ord` to connect to it via RPC? 

Thanks in advance.

**Comment by kalibox** [comment]
Self-closing this as I've managed to resolve it.

**Comment by coconutpalms** [comment]
@kalibox what did you end up doing?

**Comment by kalibox** [comment]
> @kalibox what did you end up doing?

Just used the `--cookie-file <path_to_cookie_file>` switch along with `--rpc-url <http://ip_address:8332>`

Hope this helps.
