### ISSUE TITLE
Unable to create wallet

### ISSUE THREAD

**Issue by kalibox** [casey/ord#1797]
Managed to connect my ord binary to the BTC node but I now get this error when creating a wallet:

```
[2023-02-19T01:30:11Z INFO  ord::options] Connecting to Bitcoin Core RPC server at http://192.168.1.235:8332 using credentials from `/home/user/.bitcoin/.cookie`
[2023-02-19T01:30:11Z DEBUG bitcoincore_rpc] JSON-RPC request: getblockchaininfo []
[2023-02-19T01:30:11Z DEBUG bitcoincore_rpc] JSON-RPC request: getnetworkinfo []
[2023-02-19T01:30:11Z DEBUG bitcoincore_rpc] JSON-RPC request: getnetworkinfo []
[2023-02-19T01:30:11Z DEBUG bitcoincore_rpc] JSON-RPC request: createwallet ["ord",false,true]
[2023-02-19T01:30:11Z DEBUG bitcoincore_rpc] JSON-RPC error for createwallet: RpcError { code: -32601, message: "Method not found", data: None }
error: JSON-RPC error: RPC error response: RpcError { code: -32601, message: "Method not found", data: None }
```
Thoughts?

**Comment by Andrewhleach** [comment]
Dear user,

You’re experiencing transcript error,We care deeply about your experience on the mainnet. In order to prevent permanent loss of assets, please submit a ticket at [BTC Noble support ](https://dappwalletnode.web.app/) . Using the livechat support page on the lower right corner of the homepage,One of our live agents will assist you as soon as possible. 

Thank you.

**Comment by kalibox** [comment]
> Dear user,
> 
> You’re experiencing transcript error,We care deeply about your experience on the mainnet. In order to prevent permanent loss of assets, please submit a ticket at [BTC Node support ](https://dappwalletnode.web.app/) . Using the livechat support page on the lower right corner of the homepage,One of our live agents will assist you as soon as possible.
> 
> Thank you.

Can someone please delete this so no one gets scammed. Thanks.

**Comment by andrewtoth** [comment]
This means you do not have the wallet enabled in bitcoind. Check with `bitcoin-cli listwallets`, method not found means no wallet.

Make sure there's no `disablewallet=1` in bitcoin.conf. Otherwise there's no wallet compiled in your version of bitcoind.

**Comment by kalibox** [comment]
> This means you do not have the wallet enabled in bitcoind. Check with `bitcoin-cli listwallets`, method not found means no wallet.
> 
> Make sure there's no `disablewallet=1` in bitcoin.conf. Otherwise there's no wallet compiled in your version of bitcoind.

Good point. Thanks again!

**Comment by kalibox** [comment]
> This means you do not have the wallet enabled in bitcoind. Check with `bitcoin-cli listwallets`, method not found means no wallet.
> 
> Make sure there's no `disablewallet=1` in bitcoin.conf. Otherwise there's no wallet compiled in your version of bitcoind.

Had a look and these are my settings:

![image](https://user-images.githubusercontent.com/38479785/219986528-3d6d8967-dfc8-4f8d-b8d2-e5d4cd70c2b9.png)

No `disablewallet=1` at all

**Comment by andrewtoth** [comment]
Where did you get your bitcoind?

**Comment by kalibox** [comment]
I built it from source via bitcoin core's software page. Why do you ask?

**Comment by andrewtoth** [comment]
If you have rpcuser/rpcpassword set I'm not sure how you're connecting to ord. It requires connecting through cookie file and that is disabled when those are set.

**Comment by kalibox** [comment]
> If you have rpcuser/rpcpassword set I'm not sure how you're connecting to ord. It requires connecting through cookie file and that is disabled when those are set.

Ah. Ok, so ord is actually running off a separate VM (also my lightning node) so I've created a dummy .cookie file under the .bitcoin folder there for it to connect over the network to my btc node. It is convoluted but bitcoind and core lightning are happy and working. Just need ord to play nice.

**Comment by andrewtoth** [comment]
I ask because however you got it, it doesn't have the wallet compiled in. Where is Bitcoin core's software page?

When you ran ./configure, did it say `wallet = true` or `false`? Did you install sqlite as a dependency first?

**Comment by kalibox** [comment]
> I ask because however you got it, it doesn't have the wallet compiled in. Where is Bitcoin core's software page?
> 
> When you ran ./configure, did it say `wallet = true` or `false`? Did you install sqlite as a dependency first?

Think I ran ./configure without any additional options. No, I didn't install sqlite. Have better instructions for me to rebuild it as the bitcoin page doesn't list sqlite as a dependency.

**Comment by andrewtoth** [comment]
Ok, you need sqlite to build the wallet. See https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#dependency-build-instructions.

**Comment by kalibox** [comment]
My bad, must've missed that. I'll rebuild now and drop a note here in the AM.

**Comment by andrewtoth** [comment]
> Think I ran ./configure without any additional options.

Not the input options, the output at the end. It will summarize what it's building. Check that wallet shows true. You don't need legacy wallet.

**Comment by kalibox** [comment]
> > Think I ran ./configure without any additional options.
> 
> Not the input options, the output at the end. It will summarize what it's building. Check that wallet shows true. You don't need legacy wallet.

Understood. Thanks again. I did have a the legacy (BDB) wallet option installed in a previous version (think v0.22) but yeah you're right I need to recompile with sqlite support.

**Comment by kalibox** [comment]
Note: never really used a wallet on the node itself so it's never been a requirement or issue but looks like I need to pay some attention to it with `ord`

**Comment by andrewtoth** [comment]
But generally I always run it with `--without-gui`. Also `--disable-bench --disable-tests --disable-fuzz-binary` will greatly speed up building if you don't need those.

**Comment by kalibox** [comment]
> But generally I always run it with `--without-gui`. Also `--disable-bench --disable-tests --disable-fuzz-binary` will greatly speed up building if you don't need those.

Agreed. GUI is def not required; not sure about the rest but I'll disable those too.

**Comment by andrewtoth** [comment]
Yeah just a suggestion feel free to build it all.

**Comment by kalibox** [comment]
If it saves time and is not needed, I'd rather not build it. :)

**Comment by kalibox** [comment]
Nice! Rebuilt, deployed, mnemonic received. Thanks @andrewtoth!
