### ISSUE TITLE
Undetected inscription by ordinals explorer

### ISSUE THREAD

**Issue by Aervue** [casey/ord#1802]
I am working on my own implementation of the inscribe function of ord.

This is the reveal tx of a working inscription using ord wallet (detected as an inscription by the explorer):
https://mempool.space/tx/601e7606ca012233d646152319ecfd7355270276c8f96db13759967c28b210b5

This is the reveal tx of my current implementation (undetected as an inscription by the explorer):
https://mempool.space/tx/801be915b276c09d5a92cbc07cfeb4a77e09c60456a3f0df413635d9768d42c4

Both of these transactions have the following in common and are made using a two step commit/reveal scheme:
- nSequence: 0xfffffffd
- previous_output version (the commit tx): V1_P2TR
- Size: 280 B
- Virtual size: ‎140.5 vB
- Weight: ‎562 WU
- Version: 1

When decoding the second witness data of my implementation I get the following:
```
1427594cd779c02df821c07044da816a487c398ef37f3c3228e13be28dfda311 OP_CHECKSIG OP_0 OP_IF 6f7264 OP_1 746578742f706c61696e6e3b636861727365743d7574662d38 OP_0 48656c6c6f2c20776f726c6421 OP_ENDIF
```

Which is the same as the one made by the ord wallet:
```
c7f6e73369b95a05312e858f28dd0daf56503cf78113af4524cd59e960e137f4 OP_CHECKSIG OP_0 OP_IF 6f7264 OP_1 746578742f706c61696e3b636861727365743d7574662d38 OP_0 48656c6c6f2c20776f726c6421 OP_ENDIF
```

Where `1427594cd779c02df821c07044da816a487c398ef37f3c3228e13be28dfda311` is my publicKey and assuming `c1c7f6e73369b95a05312e858f28dd0daf56503cf78113af4524cd59e960e137f4` is the ord public key.

Desired result:
- https://ordinals.com/tx/801be915b276c09d5a92cbc07cfeb4a77e09c60456a3f0df413635d9768d42c4 (should show an inscription)
- https://ordinals.com/tx/601e7606ca012233d646152319ecfd7355270276c8f96db13759967c28b210b5 (like this one does)

I am not too savy on rust so maybe I missed something, maybe the sat position is appended somewhere and not automatically computed as the first satoshi in the final output? If so, how does the data look and where is it computed?

Appreciate any tips.

**Comment by quantumcthulhu** [comment]
Same here: https://ordinals.com/tx/617b02026b7d56c85a41c07ebfd67a1186f0888fd07c59428f11b1b9cdf6a84c
