### ISSUE TITLE
Ord unresponsive to SIGINT

### ISSUE THREAD

**Issue by jorge-j1m** [casey/ord#1811]
I run `ord info` before I try any other command, and for some reason the process reads the entire `index.redb` file, resulting in VERY HIGH disk usage, but that's for another issue. The issue I'm more concerned about it's while the reading is being done (~3min in nvme ssd), the process is completely unresponsive to user signals, Ctrl + C does nothing, which isn't ideal and forced process interruption may corrupt the index file, which we also don't want. Ideal fix would be to listen for kill signals all the time and gracefully handle them without corrupting the index file. I've also faced the same unresponsiveness when running `ord index` but that's more difficult to replicate right now.

**Comment by gmart7t2** [comment]
I think it is trying to gracefully handle the control-C but it takes time. It works be nice if it would let you know it had heard you and was shutting down, otherwise you think it is "doing nothing".

It looks like maybe 6 control-Cs will force a non- graceful shutdown.

**Comment by casey** [comment]
I believe this was fixed by #1874. Let me know if I'm mistaken!
