### ISSUE TITLE
error: list requires index created with `--index-sats` flag

### ISSUE THREAD

**Issue by lepar** [casey/ord#1826]
After downloading bitcoin core, running bitcoind -txindex and after indexing all with
"ord --index-sats index"

Trying to search for sats I get the title error

Bitcoin Core Version: 24.0.1
Ord Version: 0.5.0

Obs: I didn't run it with --index-sats at first, but I read somewhere that it's default running ord index. After I ran for new blocks using --index-sats it did the same thing without it. So I'm guessing that's not the issue. 

Obs2: I'm on bitcoin's mainnet, could that have something to do it? I followed the guide, I noticed it's not implemented in mainnet yet but it also doesn't mention (at least I didn't see it) to run everything on the testnet.

**Comment by so7ow** [comment]
As I understand it, --index-sats is not the default and you have to use that flag when the index is first created for it to take effect. That is, if you created your index without --index-sats you need to start again with the flag to get the correct index.

**Comment by gmart7t2** [comment]
Obs: that's the problem. The --index-sats flag is only meaningful when the index is being created. After that it is silently ignored. 

If you want a full sats index either delete your index.redb and start again with `--index-sats` from the beginning or use `--index <path_to_index_file> --index-sats` to create a new index without deleting the old one.

**Comment by lepar** [comment]
That was my problem. I deleted the index.redb and started again with the flag and now it works. Closing this issue.
