### ISSUE TITLE
Cannot make inscriptions because ord indexer never finishes.

### ISSUE THREAD

**Issue by ZenulAbidin** [casey/ord#1863]
System information:

- ord 0.4.2 (also tested on the latest version of Ord)
- Ubuntu 22.04
- Bitcoin Core 24.0, using cookie authentication and txindex=1
- 16 GB RAM, 8 threads

Problem:

I ran `ord wallet inscribe`, and it started indexing the blocks on my node. However, indexing became progressively slower until it stops completely, sometimes on block 300,000, other times on block 370,000, or somewhere in that region.

If I interrupt the program and start again, it will never print any output (even in debug mode) or resume indexing.

Most recent log messages:

```
# ...I had to trim the beginning because it only consisted of dozens of messages similar to below.
[indexing blocks] ███████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 368627/778665[2023-03-02T04:27:21Z ERROR ord::index::updater] failed to fetch block 368660, retrying in 2s: JSON-RPC error: transport error: HTTP response too short: length 0, needed 12.
[indexing blocks] ███████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 369254/778665[2023-03-02T04:44:47Z ERROR ord::index::updater] failed to fetch block 369287, retrying in 2s: JSON-RPC error: transport error: HTTP response too short: length 0, needed 12.
[indexing blocks] ███████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 369259/778665[2023-03-02T04:45:35Z ERROR ord::index::updater] failed to fetch block 369292, retrying in 2s: JSON-RPC error: transport error: HTTP response too short: length 0, needed 12.
[indexing blocks] ███████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 370000/778665
```

**Comment by ZenulAbidin** [comment]
How much memory does this take in total? As mentioned I have 16 GB of RAM but I run a lot of stuff on this box so I tend to be on the "almost full" side of my memory usage most of the time.

**Comment by lepar** [comment]
Memory doesn't take much, I have 8gb. It takes alot of storage space though. The bottleneck is that it indexes ALL 1.9 quadrillion satoshis on a database, that takes time to do

index.redb - 118gb
BTC Blocks Folder - 513gb
BTC indexes folder - 41gb
BTC chainstate folder - 5gb

**Comment by ZenulAbidin** [comment]
I ran the command you pasted now. 5 minutes have passed and I see CPU and memory activity obviously coming from `ord` but it's not printing anything useful in info or debug levels past "Connecting to bitcoin RPC Server at ..." (which it does, but some additional verbosity would be very helpful here.)

> Message ID: ***@***.***>

Maybe it has something to do with my indexer being half-finished?

**Comment by lepar** [comment]
Are you running a bitcoin server with the index option? 

"bitcoind -txindex"

It takes time, it'll give a few errors now and then too, and warnings. You have to have everything synced and indexed first before inscribing. 
I suggest you delete the index.redb and restart it with --index-sats flag. It'll go fast until block 300k then it'll slow down cus alot of transactions starts appearing

**Comment by tudormunteanu** [comment]
can we close this?

**Comment by ZenulAbidin** [comment]
> can we close this?

Yeah, sorry about that. Forgot about this thread to be honest.
