### ISSUE TITLE
ord indexing with 0.5.1 unbearably slow

### ISSUE THREAD

**Issue by dni** [casey/ord#1877]
my progress currently is about 1 block every ~3-5 minutes a this rate i probably will never finish, not sure what is wrong. 

i also notice when i start indexing my bitcoin rpc becomes extremly unresponsive even so that my lightning node complain about bcli taking too long. 72 seconds in this case for fee estimate
```2023-03-05T15:58:56.204Z UNUSUAL plugin-bcli: bitcoin-cli: finished bitcoin-cli -rpcconnect=10.5.5.6 estimatesmartfee 2 CONSERVATIVE (74006 ms)```

my fs r/w's seems fine 
![screenshot-1678033141](https://user-images.githubusercontent.com/1743657/222972553-82474813-f9ea-4c54-8b2e-aa6089563e91.jpg)

my ram and cpu usage seems fine.
![screenshot-1678033125](https://user-images.githubusercontent.com/1743657/222972567-942d6a16-9cc5-4a33-a646-2f11a11af488.jpg)

```
root@bitcoin:~# ./ord --data-dir=./ord-data --bitcoin-data-dir=./bitcoin index
________________________________________________________________________________________________________________________________________________________________ 767689/779409
[indexing blocks] ______________________________________________________________________________________________________________________________________________ 767698/779409
[2023-03-05T09:09:43Z ERROR ord::index::updater] would sleep for more than 120s, giving up
[2023-03-05T09:09:43Z ERROR ord::index::updater] failed to fetch block 767713: JSON-RPC error: transport error: Couldn't connect to host: Resource temporarily unavailable (os error 11)
root@bitcoin:~# ./ord --data-dir=./ord-data --bitcoin-data-dir=./bitcoin index
[indexing blocks] ______________________________________________________________________________________________________________________________________________ 767721/779455
[2023-03-05T16:02:36Z ERROR ord::index::updater] would sleep for more than 120s, giving up
[2023-03-05T16:02:36Z ERROR ord::index::updater] failed to fetch block 767752: JSON-RPC error: transport error: Couldn't connect to host: Resource temporarily unavailable (os error 11)
[indexing blocks] ______________________________________________________________________________________________________________________________________________ 767734/779455
```
it also like exists randomly every hour or so.

if anyone has a clue what is going on, i would appreciate it :) for me it looks like some issue with that new version.

bitcoind is fully synced and run with -txindex on the same host

**Comment by OpenFibers** [comment]
For inscriptions, prepare 16GB memory, and 100 GB disk space for indexing file, otherwise virtual memory will slow down everything badly (in my machine).
For sat hunting, it's 32GB memory and 120GB disk space.

**Comment by dni** [comment]
damn, i did not now that it is that heavy on ram, so it is expected to never finish with < 16GB RAM?

**Comment by dni** [comment]
ok, i think i found the culprit, my hdd actually was half failing. 3 weeks later it is gone completly!
