### ISSUE TITLE
Error syncing fresh index

### ISSUE THREAD

**Issue by casey** [casey/ord#1881]
I ran into an issue syncing a fresh instance of ord on a frsh macbook. I haven't had a chance to search issues on my phone, so I don't know if it's a dupe. A picture of the error is attached.

![image](https://user-images.githubusercontent.com/1945/223009452-26a0350c-fd42-46d8-8877-fdf19ce15cab.jpeg)

**Comment by raphjaph** [comment]
Did you start bitcoins with `-txindex`?

**Comment by tyjvazum** [comment]
That seems related to these issues: https://github.com/casey/ord/issues/1872, https://github.com/casey/ord/issues/1879

**Comment by benchadwick** [comment]
Hey Casey, I am also having this problem trying to index on a new MacBook - I have noticed over these hours I've been working on it that the indexing step accurately keep increasing the max number of block and fails at the same transaction every time. 

Thank you for this work on this!

![Screen Shot 2023-03-05 at 11 53 43 PM](https://user-images.githubusercontent.com/8106690/223030081-b4d8a097-4eb0-471e-87cf-1fe02bfd25ad.png)

**Comment by mainframeconsulting** [comment]
i am also running into the same issue and same error 


root@o-btc-01:~/ord# ord index
[indexing blocks] ███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████░░░ 767429/780015[2023-03-09T13:53:11Z ERROR ord::index::updater] Couldn't receive txs Failed to fetch raw transaction: code -5 message No such mempool transaction. Blockchain transactions are still in the process of being indexed. Use gettransaction for wallet transactions.
error: failed to get transaction for a2df039d22ce84803de677328efe3a2fe82b0102d66c32f899715608babd1214

**Comment by walterliang** [comment]
me too, what is going on with this tx :a2df039d22ce84803de677328efe3a2fe82b0102d66c32f899715608babd1214
![image](https://user-images.githubusercontent.com/26303684/224322639-d8b7dd4a-3987-4b91-9599-4285242f6fbf.png)

**Comment by veryordinally** [comment]
For casey, this was -txindex missing. Fix confirmed in https://www.youtube.com/watch?v=LXrUu8WOrHo Closing this issue.
