### ISSUE TITLE
Parent and Children Inscriptions

### ISSUE THREAD

**Issue by marspoolxyz** [casey/ord#1908]
Ordinals Inscription collections works like a single Parent we can have collections  which are  Children collections, is when you inscribe as below

mime-type + data-type + parent-id(inscription id) along with the parent inscription satoshi as @raphjaph said in a podcast.

Look at this inscription with single inscription with 100 ordinals inscribed as children

### Bunny Family Tree
**Parent Ordinal**
1. https://ordinals.com/content/1804e57f2ad4a6d2663b65b373ce3ada94881d08c61035d3c1572278cfc7ad6fi0

### Childred Ordinals
1. https://ordinals.com/content/067caf7712626dfd36c99d0bdd5e952e2e07ce6133b411d93f77a9497e944f60i0
3. https://ordinals.com/content/4ec17900ca06addf8d9c00e34bcd2d3245d333f14b9ead672759620966a4b35ci0
4. https://ordinals.com/content/eb0b2e49f2bb70ce8c75fc7e3efdf9e39c34142e73ed71145e1911021569f1e0i0
5. https://ordinals.com/content/f772bc824cf3c00a5a9c707600e3c6f68a90a2481823df7f658176728c81724fi0
6. https://ordinals.com/content/87f7a292e969b25f108f6bcc22e94c55b6eadd87e84b2bd35871eb2c64303b58i0

Thank you guys
@raphjaph @casey @andrewtoth

**Comment by Psifour** [comment]
This is the inverse of the method that is being discussed for provenance. Specifically, you have children defining parents instead of parents defining children.


Ordinally has done an excellent write-up that explains what, I believe, is the current implementation goal. https://github.com/casey/ord/issues/783#issuecomment-1454314946

**Comment by veryordinally** [comment]
This is very different from what we are building with #783 
Our key idea is to have a parent specified "at birth", when the child inscription is initially made. The second key idea is to have on-chain verification that this is actually a legitimate child of the parent inscription, by spending the parent inscription in the same TX. That gives us native validation.

**Comment by LeeDewyze** [comment]
> This is very different from what we are building with #783 Our key idea is to have a parent specified "at birth", when the child inscription is initially made. The second key idea is to have on-chain verification that this is actually a legitimate child of the parent inscription, by spending the parent inscription in the same TX. That gives us native validation.

Does this mean that I can only add one child to a parent, because the parent inscription id has already been consumed by the first child?
