### ISSUE TITLE
Installing ORD on iMAC

### ISSUE THREAD

**Issue by AdmiralNeo** [casey/ord#1911]
The command in docs installs ORD in BIN-folder. But when i run "ord --version" I get "command not found" - so I guess ORD not installed. Anybody knows how to handle this properly for iMAC?

**Comment by so7ow** [comment]
Try `~/bin/ord --version`

**Comment by AdmiralNeo** [comment]
> Try `~/bin/ord --version`

THX bro - it worked! Sorry for the stupid beginners question.
