### ISSUE TITLE
Cannot restore wallet from seed

### ISSUE THREAD

**Issue by beppeben** [casey/ord#1912]
After a resync, I tried to restore my previously created wallet with

    ord wallet restore "my seed words"

But then after running

    ord wallet transactions

I get the following error

    error: wallet "ord" contains unexpected output descriptors, and does not appear to be an `ord` wallet, create a new wallet with `ord wallet create`

Any idea how to fix it?

**Comment by beppeben** [comment]
Fixed by deleting the wallet, then restoring it again.

**Comment by estevanpedro** [comment]
Worked for me
```
rm -r .bitcoin/wallets
 ```

 ```
 ord wallet create 
```
or `ord wallet recover ...`
```
ord wallet receive
```
