### ISSUE TITLE
Fee not calculated correctly when using parent inscription

### ISSUE THREAD

**Issue by veryordinally** [casey/ord#1916]
There is a fee calculation bug, and effective fee rate is about twice as much as required when using a parent inscription.

**Comment by kvnn** [comment]
Hi. Can you share how you're "using a parent inscription" ? I can't find this anywhere in the docs. Are you on https://github.com/casey/ord/pull/1869 ?

**Comment by veryordinally** [comment]
This is a bug on work-in-progress #1869
