### ISSUE TITLE
Import mnenomic words to sparrow wallet, the addresses did not match

### ISSUE THREAD

**Issue by Eleven711** [casey/ord#1925]
hey ,  I use command `ord wallet create` , and get the mnenomic words.  I imported them to sparrow wallet as the below steps:

1. Choose script type : Taproot
2. Import mnenomic words,  and leave the passphrase for none
3. Import Custom Derivation Keystore m/86'/0'/0'/0 
4. Check the Master fingerprint , is equal to I get from ord
5. Apply, and I got 20 addresses. 
6. But none of the 20 addresses are not the address I get from ord `ord wallet receive.`
Any help ? Thank you.

**Comment by refazi** [comment]
increase the gap limit on sparrow to 2000

**Comment by Eleven711** [comment]
> Every call to ord wallet receive function will generate a new receiving address. This is expected.

correct, I see. The command `ord wallet receive` actually calls rpc getnewaddress method, However i think getnewaddress  start from m/86'/0'/0'/0  and then index ++.

**Comment by satoshi0770** [comment]
if im not mistaken
ord wallet receive
generates with !ifchange=true
using derivation path for "change" addresses.
you should see the change addresses in sparrow.
do those change addresses align with ord wallet receive address?

**Comment by Eleven711** [comment]
I see my addresses in sparrow wallet. I input wrong path : m/86'/0'/0'/0/0/*. It should be m/86'/0'/0'/0/* .

**Comment by Psifour** [comment]
This last part (and @satoshi0770's statement) are both correct.

It is important to note that most _standards-compliant_ software will not need you to specify the derivation path manually unless you forget to select Taproot. This is true of ord and Sparrow as they both use the derivation paths specified in BIP 86 for Taproot.
