### ISSUE TITLE
How to send Funds from my Ord Wallet without my Inscriptions

### ISSUE THREAD

**Issue by TheRealFuture42** [casey/ord#1930]
How do I get my balance of Sats/BTC out of my Ord Wallet? Or are they forever linked to my inscriptions? I have some inscriptions in my Ord Wallet and would like to keep them in the Ord Wallet!

**Comment by Psifour** [comment]
`ord wallet send bc1targetaddress Xsats` or `ord wallet send bc1targetaddress Xbtc` where X is the amount of sats or BTC to send.

Technically it is structured as
`ord wallet send <address> <outgoing>`
"Outgoing" can be an inscription ID, a number of sats with the suffix "sats", or a decimal amount of Bitcoin with the suffix "btc".

**Comment by sslisen** [comment]
> 
Thanks for the info.
And i would like to know where Can I find this command? Is it in ordinal doc?

**Comment by Magicking** [comment]
This command is for the `ord` client, you can find guide links to install it on the from the [Discord](https://discord.gg/ordinals) in this issue https://github.com/casey/ord/issues/1062#issuecomment-1480459340
