### ISSUE TITLE
ADJ

### ISSUE THREAD

**Issue by ADJwot** [casey/ord#1933]

**Comment by ADJwot** [comment]
GM

**Comment by Psifour** [comment]
Welcome to the Ordinal Project Github. It would appear this issue has no associated information about an outstanding issue/design feature of the codebase, please provide a detailed title and description of your issue or close this to reduce spam of the issue tracker.

**Comment by ADJwot** [comment]
![IMG20230320183516.jpg](https://user-images.githubusercontent.com/83719013/226390856-30b6e230-98fe-414b-b089-b6398fce0f4f.jpg)

**Comment by ADJwot** [comment]
These ordinals were stolen from my wallet and are now being sold at the bottom of the market

**Comment by ADJwot** [comment]
bc1pqjkdu4esvmgadxyfza3cuyjuhdw42s8yd38f9cttxfc04h0knd2su5dxdm

**Comment by ADJwot** [comment]
Tell me can you help me

**Comment by ADJwot** [comment]
Dear developers, everything was lost in my wallet, it all started from the moment I bought two nfts of a fancy monkey that never reached me, then everything disappeared, someone unknown transferred the remaining four nfts from my wallet and I do not know who to turn to for help
 
 
С Уважением зам.гл.инженера.ООО «Смарт Групп Строй»
Доля Алексей Николаевич т.  89172742191

**Comment by ADJwot** [comment]
bc1pqjkdu4esvmgadxyfza3cuyjuhdw42s8yd38f9cttxfc04h0knd2su5dxdm everything is gone from this wallet
 
 
 
С Уважением зам.гл.инженера.ООО «Смарт Групп Строй»
Доля Алексей Николаевич т.  89172742191

**Comment by ADJwot** [comment]
https://ordinalswallet.com/address/bc1pqjkdu4esvmgadxyfza3cuyjuhdw42s8yd38f9cttxfc04h0knd2su5dxdm
 
 
С Уважением зам.гл.инженера.ООО «Смарт Групп Строй»
Доля Алексей Николаевич т.  89172742191

**Comment by veryordinally** [comment]
ordinalswallet.com is unrelated to us. Please reach out to their support to get help. AFAIK that wallet has a model where you are not in control of your private keys, so the risk of hacks with such a model is significant unfortunately.

**Comment by nammaki** [comment]
> ordinalswallet.com is unrelated to us. Please reach out to their support to get help. AFAIK that wallet has a model where you are not in control of your private keys, so the risk of hacks with such a model is significant unfortunately.

When I click on "create wallet" the first thing it says is "Ordinals wallet is a non-custodial BTC wallet that allows users to view and store BTC and Ordinals NFTs" so I think it's just a non-custodial web wallet 🤷
