### ISSUE TITLE
Incorrect wallet restore command example shown on ordinals.com

### ISSUE THREAD

**Issue by so7ow** [casey/ord#1944]
At this location: [Importing into ord wallet](https://docs.ordinals.com/guides/collecting/sparrow-wallet.html#importing-into-ord-wallet)

The restore command is listed as: 
```
ord --wallet ord_from_sparrow restore "BIP39 SEED PHRASE"
```

The correct syntax would be:
```
ord --wallet ord_from_sparrow wallet restore "BIP39 SEED PHRASE"
```

**Comment by Psifour** [comment]
Confirmed this issue.
@gmart7t2 has already submitted a fix for the missing `wallet` command in that line.
