### ISSUE TITLE
I got "wallet does not contain enough cardinal UTXOs, please add additional funds to wallet."

### ISSUE THREAD

**Issue by sslisen** [casey/ord#1950]
My computer runs bitcoin core, and has synchronized the full node and index synchronization. 
I created a wallet with ord and funded. Currently, the wallet has 1 UTXO and a btc balance of 0.00144868BTC. When I use the inscribe command, it prompts "wallet does not contain enough cardinal UTXOs, please add additional funds to wallet."
![image](https://user-images.githubusercontent.com/59131974/226169736-ea9d1499-6536-41dc-9118-cfe880ea3b22.png)

**Comment by Psifour** [comment]
How large of a file are you attempting to inscribe and at what fee rate?

**Comment by sslisen** [comment]
> 

only 119Kb
