### ISSUE TITLE
How to send btc to cex by bitcoin core wallet.

### ISSUE THREAD

**Issue by sslisen** [casey/ord#1953]
I ran full node on my PC, and I installed ordinal.
I recently inscribed sevral inscriptions, and I hold the inscriptions in my wallet.
But now, I want to send some BTC to binnace, how to send btc without sending my inscriptions out.
I don't want to ruin my inscriptions.

**Comment by veryordinally** [comment]
I would recommend to do that using Sparrow. Using the bitcoin core wallet is more error prone in my experience. See https://docs.ordinals.com/guides/collecting/sparrow-wallet.html for how to set up Sparrow.

**Comment by sslisen** [comment]
thank you very much for the useful info.
