### ISSUE TITLE
How to make ordinal automatic indexing

### ISSUE THREAD

**Issue by sslisen** [casey/ord#1974]
If you stay for too long, it will cause the ordinal to be synchronized for a long time when you use it next time.
Is there a way to make ordinal continuous automatic indexing? (Just like bitcoin core do. If I keep bitcoin core open, then it will automaticly snyc the block data)

**Comment by toddynho** [comment]
Just add a cron in crontab:

#run ord index every minute
* * * * * /path/to/target/release/ord index

**Comment by sslisen** [comment]
Oh!
That's a brilliant move.
Thank you for this tips.

**Comment by nammaki** [comment]
https://github.com/casey/ord/issues/1946, I think running every minute will def hit any reorgs that happen so probably better to do every hour or more rather than every minute 🤔

**Comment by toddynho** [comment]
@nammaki I was on vacation when the reorg issue hit - ended up just reindexing... was there some discussion around handling reorgs and indexing that you could point me to? All good if not handy, I will look around as well.

**Comment by nammaki** [comment]
@toddynho, in addition to the issues linked in https://github.com/casey/ord/issues/1946 there was also https://github.com/casey/ord/discussions/1951 but the solution provided so far is just a manual reindex 😭
