### ISSUE TITLE
Add "--rpc-url" option to ord help

### ISSUE THREAD

**Issue by somoza** [casey/ord#1980]
When you run `ord help` you get a list of options but `"--rpc-url"` isn't present. Would be nice to have it, that saved me and I had to guess :)

**Comment by gmart7t2** [comment]
I see it sorted alphabetically right between `--regtest` and `--signet`:

```
$ ord-0.5.1 --help | grep -C4 rpc-url

    -r, --regtest
            Use regtest. Equivalent to `--chain regtest`.

        --rpc-url <RPC_URL>
            Connect to Bitcoin Core RPC at <RPC_URL>.

    -s, --signet
            Use signet. Equivalent to `--chain signet`.
$ 
```

I wonder why you don't.

**Comment by soenkehahn** [comment]
Yeah, I see it too in the help. @somoza, assuming this issue is addressed, I'll close it. Feel free to re-open if that's not correct.
