### ISSUE TITLE
Inscription was successfully inscribed in Bitcoin but its detail couldn't be displayed on oridinals.com. Maybe an index issue.

### ISSUE THREAD

**Issue by 6789tc** [casey/ord#2038]
The Inscription Genesis transaction could be perfectly found in [oridinals.com](https://ordinals.com/), however, when I click on the link to inscription detail it returns "Internal Server Error".

Inscription Genesis txn: https://ordinals.com/tx/df968aa38e86d4df52ce27687625009d32e2ac03840c2d6b883a0ae94e783f45

<img width="1574" alt="Screen Shot 2023-04-23 at 22 04 32" src="https://user-images.githubusercontent.com/130814596/233891393-43e71393-bbcb-48ea-8f67-04c209dd13fb.png">

Inscription detail: (Internal Server Error)
https://ordinals.com/inscription/df968aa38e86d4df52ce27687625009d32e2ac03840c2d6b883a0ae94e783f45i0

Can someone help me understand how is that possible? Thanks.

**Comment by gmart7t2** [comment]
This issue was fixed in ord 0.5.2 last week by this PR: https://github.com/casey/ord/pull/1971

The index needs rebuilding after switching to ord 0.5.2.

**Comment by veryordinally** [comment]
Updated `ord` on `ordinals.com` to `0.5.2` and rebuilt index. `https://ordinals.com/tx/df968aa38e86d4df52ce27687625009d32e2ac03840c2d6b883a0ae94e783f45` no longer gives an internal server error.

**Comment by gmart7t2** [comment]
> The index needs rebuilding after switching to ord 0.5.2.

The index was rebuilt. This issue can now be closed.
