### ISSUE TITLE
how can I get json content of brc20

### ISSUE THREAD

**Issue by flyhigh** [casey/ord#2078]
Is there any api that can get  json content of brc20?

**Comment by zhwindy** [comment]
Maybe NFTScan Developer API
https://developer.nftscan.com

**Comment by GaloisField2718** [comment]
> Is there any api that can get  json content of brc20?

Maybe via ord indexer no ? You should get access to inscribe data at least in hex format into psbt

**Comment by casey** [comment]
Discussion of BRC-20 is off topic.
