### ISSUE TITLE
自建服务没有显示sat字段

### ISSUE THREAD

**Issue by wo4zhuzi** [casey/ord#2088]
<img width="1067" alt="image" src="https://github.com/casey/ord/assets/20334885/cc9364ec-f9c0-4be8-8cd4-29b38aba8b54">
查询 https://ordinals.com/inscription/fea24db7184668433e5cc0a6ba55b7655c2f8e0159909096634ba6de0afa837bi0 有返回sat字段，自建的服务没有sat字段，请问一下是什么原因

**Comment by wanyvic** [comment]
you should start ord with --index-sat argument
