### ISSUE TITLE
Want to get paid to work on ordinals?

### ISSUE THREAD

**Issue by casey** [casey/ord#272]
I've been working with @terror full-time for a few months now, but he's heading back to school at the end of August, so I'll be looking to hire someone to work with me on ordinals starting in September.

Pros:
- Work closely with an experienced Rust and Bitcoin developer
- All Rust
- All Bitcoin
- All ordinals
- All CC0-licensed open source, publicly developed on GitHub
- High quality standards, test-driven development

Cons:
- I can't pay a lot! ~$30/hour paid in bitcoin.

If you want to work with me, but you would need to be paid more (even much more), send me your info with your salary requirements. I might not be able to make it work now, but I might be able to make it work down the line.

I'm looking for someone who already has some understanding of both Rust and Bitcoin. It's not important that you've been doing both for years, but you should know how the basics of Rust, and a bit about the basics of Bitcoin.

My working hours are currently 10am to 6pm M-F Pacific Time, so you should be free then, and have a quiet place where you can work and be on a video call with me.

If you're interested, send me an email at casey@rodarmor.com with a little bit about yourself, any personal links, a resume if you have one, and ideally some links to some open-source work you've done. Small, personal projects are totally fine!

**Comment by Anthonyslav** [comment]
I will be happy to work with you. Though I am a solidity developer, I can learn rust if that is what the job requires.

**Comment by casey** [comment]
Thanks for the interest! Rust is a very challenging, and going from zero to one, i.e. going from not ever having written rust, to being a proficient novice, can take a long time, so I'd be hesitant to take on someone who didn't have basic proficiency.

**Comment by Anthonyslav** [comment]
I am a programmer already I know like 5 other programming languages so adding a sixth isn't going to be hard. I am a fast learner trust me and I have studied Bitcoin. So I am worth the shot

**Comment by LevDev2017** [comment]
Hello, nice to meet you.
I have rich experience in development of Dapps in rust language on various networks such as Solana, Polkadot and Cosmos.
If you are interested in my skills and experience, please share your ideal project.

**Comment by casey** [comment]
I haven't thought carefully about how to vet people that I'd potentially work with. I think I need to mark some issues as good first issues, and people can take a stab at them and see if it's a good fit.

**Comment by LevDev2017** [comment]
Ok, I see.
What do you want to start the work?

**Comment by LevDev2017** [comment]
Hello, when can I participate in your project?

**Comment by casey** [comment]
Alright, sorry for the delay!

I think that for now, I'm going to focus less on trying to find a paid contributor, and more on trying to make the project more accessible to unpaid contributors. I'd like to eventually find a paid contributor, but I want to first experiment with getting more community involvement.

To start with, I labeled a bunch of issue with "good first issue":

https://github.com/casey/ord/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

If either of you feel like it, you could take a crack at one of them. However, I think for now, finding paid contributors is not a priority, so only do it if you're interested.
