### ISSUE TITLE
Ordinal Clock

### ISSUE THREAD

**Issue by casey** [casey/ord#296]
The current clock is only based on height, so it's really a bitcoin clock. Add an ordinal version with the following:

- indicate rarity
- show offset/third in block using sub-dial
- name
- degree?
- time?
- number?
- decimal?

The best way to start this issue is with a PR that adds a dial to the clock which shows the offset.

Expose this clock at /clock/ORDINAL

**Comment by raphjaph** [comment]
What tool did you use to generate the .svg for the clock?

**Comment by casey** [comment]
It's a hand-modified version of the SVG from this tutorial: https://medium.com/the-andela-way/create-a-pure-css-clock-with-svg-f123bcc41e46

SVG is pretty dope, and doing it by hand isn't that bad.

**Comment by raphjaph** [comment]
Thanks for the pointer! Have never tried to craft an SVG by hand but seems straight forward enough.

I was thinking of adding the ordinal type colors (uncommon, rare, epic and legendary) and number of each type in existence somehow. Something like this perhaps: [excalidraw](https://excalidraw.com/#room=687c5180fac9f8713b64,JwTzSksn2ikGDz8Dbx36hA)

**Comment by casey** [comment]
I think I like the clock to be mostly monochrome, and a little mysterious. One thing I definitely want is #386, including the current height on the block. Note that there will eventually be two versions of the clock, one which is just based on the block height, and another which will be based on an ordinal. (The latter will have a little sub-dial which shows the position of the ordinal in the block.)

**Comment by casey** [comment]
I also just made #387, adding SVG `<title>`s to the elements of the clock, which appear on hover. This would be a good way to add some explanations to the clock without cluttering it visually.
