### ISSUE TITLE
Socket or port exhaustion when making fast RPC calls to bitcoin core

### ISSUE THREAD

**Issue by casey** [casey/ord#309]
`JsonRpc(Transport(SocketError(Error { kind: TimedOut, message: "connection timed out" })))`

This is due to using too many sockets or ports. Probably ports, specifically local ephemeral ports.

This is the rust-jsonrpc issue: https://github.com/apoelstra/rust-jsonrpc/issues/67

Need to reuse the socket, or add hyper transport to rust-jsonrpc.

Update: I'm not actually sure what's going on here. We tried the socket-reusing version and it didn't help.

We should:
- Test again with the latest PR version
- Do a comparison with `bitcoin-cli`. If `bitcoin-cli` doesn't have this problem, then it's a good indication that the issue is in jsonrpc.

**Comment by VirtuallyThere** [comment]
Potentially explore moving to https://github.com/paritytech/jsonrpsee

**Comment by raphjaph** [comment]
maybe try again with this fix: https://github.com/apoelstra/rust-jsonrpc/pull/72
