### ISSUE TITLE
All RPCs to bitcoind timeout

### ISSUE THREAD

**Issue by raphjaph** [casey/ord#381]
I've been trying to play around with `ord` a bit, but most of the commands that make calls to `bitcoind` timeout. Here are some I tried:

```bash
ord server --address 127.0.0.1
[2022-08-30T13:36:19Z ERROR ord::subcommand::server] JSON-RPC error: transport error: Didn't receive response data in time, timed out.
```
```bash
ord find 0
error: JSON-RPC error: transport error: Didn't receive response data in time, timed out.
```
```bash
ord list 6359f0868171b1d194cbee1af2f16ea598ae8fad666d9b012c8ed2b79a236ec4:1
error: JSON-RPC error: transport error: Didn't receive response data in time, timed out.
```
```bash
ord wallet balance
error: Rpc(JsonRpc(Transport(Timeout)))
```
There seem to be some related issues (#308 and #273) but not sure if they are applicable. Do I perhaps have to change something in `bitcoin.conf` of my `node` to allow a higher timeout threshold? My setup is this: `bitcoind` on a RaspberryPi in same network, `bitcoin-cli ` on a Mac and tunneling the RPC with `ssh -L 8332:localhost:8332 node` to the Mac.

**Comment by casey** [comment]
I think the issue is that the only form of auth we support is via the `--cookie-file` option. If `--cookie-file` isn't passed it looks in the default bitcoin data dir, and tries to read a cookie file from there. Maybe it's finding a cookie file in a bitcoin data dir on your machine, using it, and it doesn't match with the remote machine?

You could try copying the cookie file to your mac, and then using `--cookie-file path-to-cookie-file`.

Does bitcoin-cli work locally? How are you authing?

**Comment by raphjaph** [comment]
I use the script `bitcoin/share/rpcauth/rpcauth.py` to generate credentials for my computer, put those in the `bitcoin.conf` of my node (`rpcauth=username:salt$passwordHMAC`). The cookie I create manually by putting `username:password` in a file on my computer. I then use bitcoin-cli locally like this:
```
bitcoin-cli -rpccookiefile=/Users/raphael/bitcoin-rpc-cookie getblockchaininfo
```

I'm running ord like this: 
```
./target/debug/ord --cookie-file /Users/raphael/bitcoin-rpc-cookie info
```

Currently I have these optimizations in my bitcoin.conf:
```
# RaspberryPi optimizations
rpcthreads=16
maxconnections=40
maxuploadtarget=5000
dbcache=1024
maxorphantx=10
maxmempool=300
```
Do I maybe have to increase/decrease some values to make it work?

**Comment by raphjaph** [comment]
I've stopped all other consumers of the RPC (clightning, electrs,...) and  added these options:
```
rpcworkqueue=64
rpcthreads=64
rpctimeout=10000
timeout=10000
```
Unfortunately I still get:
```
./target/debug/ord --cookie-file /Users/raphael/bitcoin-rpc-cookie find 0
error: JSON-RPC error: transport error: Didn't receive response data in time, timed out.
```
Maybe the timeout of `ord` is set to aggressively?

**Comment by casey** [comment]
Very odd! We talked a little bit about this, but didn't really come to any conclusions. I remember you said that it's timing out on a request for the block hash at a given height, which should be fast enough that the default timeout isn't too aggressively. How long does it take to time out?

**Comment by raphjaph** [comment]
```bash
time RUST_LOG=debug ./target/debug/ord --cookie-file /Users/raphael/bitcoin-rpc-cookie list 6359f0868171b1d194cbee1af2f16ea598ae8fad666d9b012c8ed2b79a236ec4:1

[2022-09-05T12:57:13Z INFO  ord::index] Connection to Bitcoin Core RPC server at 127.0.0.1:8332 using credentials from `/Users/raphael/bitcoin-rpc-cookie`
[2022-09-05T12:57:13Z DEBUG bitcoincore_rpc] JSON-RPC request: getblockhash [0]
[2022-09-05T12:57:28Z DEBUG bitcoincore_rpc] JSON-RPC failed parsing reply of getblockhash: JsonRpc(Transport(Timeout))
error: JSON-RPC error: transport error: Didn't receive response data in time, timed out.
RUST_LOG=debug ./target/debug/ord --cookie-file  list   0.10s user 0.16s system 1% cpu 15.071 total
```

Don't know if I'm using `time` correctly but it takes more than 10 seconds.

**Comment by casey** [comment]
Let me know if this is still an issue.
