### ISSUE TITLE
Ordinals twitter bot that posts new rares and exotics

### ISSUE THREAD

**Issue by casey** [casey/ord#425]
It would be cool if we tweeted every time a rare or exotic ordinal was mined. Not sure how this would work, so first step is to spec it out.

**Comment by raphjaph** [comment]
Yes, I like this idea. It would be similar to [OP_RETURN Bot](https://twitter.com/OP_RETURN_Bot). We could use some sort of webhook stuff or just post all new inscriptions to an RSS feed on ordinals.com that a bot can just read easily.

**Comment by raphjaph** [comment]
I've reserved @ord_bot on twitter

**Comment by raphjaph** [comment]
The name kinda looks like robot haha

**Comment by casey** [comment]
Cleaning house. I think issues like this are best tracked somewhere else. Maybe a discussion? I want to keep the issues more focused and near-term.
