### ISSUE TITLE
Rename `wallet fund` to `wallet address`

### ISSUE THREAD

**Issue by casey** [casey/ord#441]
I don't think we're going to use separate funding and ordinal addresses.

**Comment by sokratisvas** [comment]
Hi, I would like to help. Just to make sure I understand the task, you want to replace ```wallet fund``` with ```wallet address``` in the ```tests/wallet.rs``` file?
https://github.com/casey/ord/blob/d3ed942cea2510d0f504bb1c03ecc4068d6c7dd8/tests/wallet.rs#L80-L84

**Comment by casey** [comment]
Yup, the idea is to change the command from being called `ord wallet fund` to `ord wallet address`. The test, as well as the name of the subcommand itself, will both need to change.

**Comment by casey** [comment]
This command is gone, so this can be closed for now.
