### ISSUE TITLE
Add benchmark for index performance and size

### ISSUE THREAD

**Issue by casey** [casey/ord#456]
There are a bunch of performance optimizations that would be nice to explore, but they're all blocked on having an easy way to benchmark the index.

We should have a single command (probably 'cargo bench') that benchmarks the index over some reasonable workload of blocks and transactions. These blocks and transactions should be generated on the fly, so we aren't benchmarking interactions with bitcoin core.

**Comment by VirtuallyThere** [comment]
@casey Not sure we did everything in #488 that you had in mind here, but should be linked.

**Comment by casey** [comment]
I think this can be closed now that we have a basic benchmark. If we need a simulated workload, we can explore that when it becomes necessary.
