### ISSUE TITLE
Build index in parallel

### ISSUE THREAD

**Issue by casey** [casey/ord#458]
The ordinal index is currently single threaded. It would be nice to figure out how to build it in parallel. One thing that will reduce parallelism is the fact that redb writers must be serialized.

The two sources of parallelism I can think of are:

- Process blocks in parallel
- Process transactions in parallel

Straw man proposal:

- Create queue of transactions to process
- Create a pool of workers that grabs transactions from the queue, figures out which ranges are in the inputs, which ranges are in the outputs
- Workers then either commit those changes to the database, or communicate them to a writer thread that writes them to the database

This is blocked on #111, benchmarks, since you can't optimize what you can't benchmark.

**Comment by VirtuallyThere** [comment]
Started looking at literature after our discussion last night. Found an interesting PhD thesis https://tuprints.ulb.tu-darmstadt.de/19668/1/Identification_of_Suitable_Parallelization_Patterns_for_Sequential_Programs_Ul_Huda.pdf

**Comment by casey** [comment]
I think this is either impossible or will complicate the codebase enormously, so closing for now.
