### ISSUE TITLE
Simple instructions for ordinal hunting

### ISSUE THREAD

**Issue by casey** [casey/ord#471]
Something like:

- btc = sats
- sats = ordinals
- check output for ordinals (command line recommended, otherwise use the index)

**Comment by VirtuallyThere** [comment]
I would recommend hunting for ordinals in your UTXO set only locally, so you don't dox your stack. 

If you have an Electrum wallet, you can easily get a list of all the outputs you control by running
```
for o in map(lambda x:x.get('prevout_hash')+':'+str(x.get('prevout_n')), listunspent()):
  print(o)
```
You can then get all the ordinal ranges for those outputs by piping them into `xargs ord list` (assuming you have PR #510 and an up to date mainnet index) and then hunt in those ranges.

**Comment by casey** [comment]
Done here: https://docs.ordinals.com/hunting.html
