### ISSUE TITLE
Can't compile ord due to  `LISTENERS` type

### ISSUE THREAD

**Issue by jurraca** [casey/ord#472]
This is probably on me, but wanted to report in case. Compiling ord with `cargo build`, cargo version `1.61.0`, rustc version `1.61.0` yields the following error: 
```
error[E0015]: cannot call non-const fn `std::sync::Mutex::<Vec<axum_server::Handle>>::new` in statics
   --> src/main.rs:110:40
    |
110 | static LISTENERS: Mutex<Vec<Handle>> = Mutex::new(Vec::new());
    |                                        ^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: calls in statics are limited to constant functions, tuple structs and tuple variants

For more information about this error, try `rustc --explain E0015`.
error: could not compile `ord` due to previous error
``` 
Reading the docs, the error seems correct, `axum_server::Handle` is non-constant, but idk (rust noob).

**Comment by casey** [comment]
This actually changed recently. Rust is complaining about using `Mutex::new` in a constant, which used to be non-const but is now const as of rust 1.63. Try upgrading to rust 1.63 and trying again.

**Comment by jurraca** [comment]
works :+1: closing

**Comment by casey** [comment]
Nice!
