### ISSUE TITLE
Command-line-processing friendly output format for all ordinal ranges belonging to a given output

### ISSUE THREAD

**Issue by VirtuallyThere** [casey/ord#491]
Make it possible to get all relevant ordinals info for a given output (txid:vout) in a format that is friendly for command line processing with grep, awk, sort and the like. Probably a simple tab separated, one record per line format is easiest.

Possibly also consider json format for processing with jq (https://stedolan.github.io/jq/) - possibly by passing a `--json` flag to commands that make output JSON (that would then become a separate issue to apply to all relevant commands).

**Comment by casey** [comment]
Sounds good to me! Let's do whatever's friendliest for awk, sed, tab, grep, and the like. We can then think about adding a `--json` flag that switches to JSON output.

**Comment by casey** [comment]
We should probably have more specific issues than this.
