### ISSUE TITLE
Exponential backoff for RPC calls to bitcoind not reset after successful calls

### ISSUE THREAD

**Issue by VirtuallyThere** [casey/ord#501]
The exponential backoff (important currently to deal with #309) is not reset after a successful RPC call, so we give up once we have encountered 5 errors in total. The error counter should be reset after a successful RPC call to implement expected exponential backoff behavior.

**Comment by casey** [comment]
Good catch!

**Comment by VirtuallyThere** [comment]
The fix is obviously trivial (reset `errors` to 0 after successful call), but given the bug is currently just in draft PR #495 this is more of a reminder.

**Comment by casey** [comment]
I think this is fixed
