### ISSUE TITLE
Implement error handling for bitcoind RPC calls

### ISSUE THREAD

**Issue by VirtuallyThere** [casey/ord#504]
We need error handling for transient errors in calls to bitcoind, i.e. all calls to the bitcoin core RPC client, especially for the (potentially long running) index subcommand. Currently, it fails after it encounters any error. This is particularly bad on a Mac, given we have #309 

Ideally, we implement a retry with exponential backoff and a limit for all RPC calls as some sort of wrapper to Client? We already have this on the background-block-fetch branch (but see #501, which is trival to fix fortunately)

**Comment by VirtuallyThere** [comment]
Mostly addressed with #508 for the most annoying aspect of this (#309)
It would be nice to extend the error handling to all RPC calls but that's more of a nice to have.

**Comment by casey** [comment]
I think this can be closed, but feel free to reopen if it's still an issue. It would be nice to handle transient errors in the client somehow, instead of in the indexing code.
