### ISSUE TITLE
Resuming indexing consistently fails with "Could not find outpoint in index"

### ISSUE THREAD

**Issue by VirtuallyThere** [casey/ord#505]
After we implemented #496, resuming indexing consistently fails on the main chain starting from block heights above 150000 or so, that is if we run `ord index --height-limit 150000` (starting with no index) and then run `ord index` again, it immediately fails with:
```
[2022-09-09T16:31:55Z INFO  ord::index] Block 149999 at 2011-10-20 13:40:14 UTC with 17 transactions…
[2022-09-09T16:31:55Z INFO  ord::index] Block receiver disconnected: sending on a closed channel
error: Could not find outpoint in index
```

Resuming indexing works for smaller block heights. 

It seems the index is inconsistent in some way. I had not seen this behavior before we implemented #496

**Comment by casey** [comment]
Fixed! I made an off-by-one error in #495.
