### ISSUE TITLE
Commit every N seconds instead of every N blocks

### ISSUE THREAD

**Issue by casey** [casey/ord#524]
I'm syncing an index on my laptop, and have had to ctrl-c it a few times, and in later stages of syncing, this can lose on average 2.5 minutes of work, since each block is taking 200-300ms to sync.

This makes me think that in fact, we should sync every N seconds instead of every N blocks. Maybe every 60 seconds, since that's likely to keep I/O bandwidth saturated, but will only lose on average 30 seconds of work if you have to stop and start the index.

**Comment by bsta9** [comment]
Welcom
