### ISSUE TITLE
Allow authenticating to bitcoind with username and password

### ISSUE THREAD

**Issue by casey** [casey/ord#527]
Currently, the only auth method for bitcoin core RPC is via cookie file. It would be nice if it were possible to auth with a username and password, in case the cookie file isn't available.

Passwords shouldn't be passed on the command line, so we should probably accept the username and password via environment variable.

**Comment by casey** [comment]
Closing. If you want or need this, please comment!

**Comment by Jossec101** [comment]
Def we need this, many bitcoind are using username/password @casey

**Comment by brocciu** [comment]
Hello, I and all the raspiBlitz community desperately need this !
