### ISSUE TITLE
Speed up rarity check in index

### ISSUE THREAD

**Issue by casey** [casey/ord#724]

**Comment by VirtuallyThere** [comment]
I performed some analysis of the distribution of ordinal epochs that we encounter in the rarity checking during indexing various segments of the mainnet:
![Screenshot 2022-10-28 at 17 33 50](https://user-images.githubusercontent.com/11798624/198677362-0948f3a6-40d0-413c-b41b-b326f738ea13.png)

I also performed a head-to-head comparison of binary search and linear search (by running both versions of the method and got these results from the profiler, indexing from blocks 700000 to 701000:

![Screenshot 2022-10-28 at 17 39 35](https://user-images.githubusercontent.com/11798624/198677660-1e6a7fbf-822e-46c5-b0a8-203cb4446ea7.png)

So binary search takes a total time of about 59s, and linear search takes about 7s, indicating a speedup of a factor of more than 8.
