### ISSUE TITLE
Panic in redb during indexing 

### ISSUE THREAD

**Issue by VirtuallyThere** [casey/ord#752]
ord stops with a panic when indexing mainnet from the genesis block:

```
[2022-10-30T20:26:43Z INFO  ord::index::updater] Committing at block height 200001, 16630258 outputs traversed, 422726 in map, 12785452 cached
[2022-10-30T20:26:43Z INFO  ord::index::updater] Flushing 422726 entries (17.6% resulting from 2401326 insertions) from memory to database
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TryFromIntError(())', /Users/uc/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.8.0/src/tree_store/btree_base.rs:983:60
```

Will further investigate and see if this is reproducible, and generate backtraces.

**Comment by VirtuallyThere** [comment]
This actually seems to be some sort of Heisenbug. I had gotten it two times in a row initially, at different block heights, using the same binary, on the same machine, starting from a non-existent redb. Once I set `RUST_BACKTRACE=1`, it just keeps on running on three runs now - did two up to block 250k, no issues, and now have one running with a heightlimit of 500k, and that is currently at block 465k and still going.

@casey would appreciate your insights into how you would approach debugging this. Just from the source location redb-0.8.0/src/tree_store/btree_base.rs:983 this might be a redb issue? The corresponding code in redb is the last line here:

```
        let new_num_pairs = if overwrite { num_pairs } else { num_pairs + 1 };
        self.page.memory_mut()[2..4]
            .copy_from_slice(&u16::try_from(new_num_pairs).unwrap().to_le_bytes());
```

**Comment by VirtuallyThere** [comment]
Fixed in redb

**Comment by random9brat** [comment]
had the same error mapping the index tree, got error at exactly 300.000 block.... any chance someone could help me?
