### ISSUE TITLE
Don't lose ordinals if reveal transaction is not mined

### ISSUE THREAD

**Issue by casey** [casey/ord#769]
It's currently possible to lose ordinals by broadcasting a commit transaction, but then losing the reveal transaction. We should avoid this.

Ideas:

- Save the reveal transaction to disk. Doesn't help if the reveal transaction is invalid, and so can never be broadcast.
- Add the reveal transaction descriptor, including the private key, to the bitcoin wallet, so bitcoin can spend it.
- Save the reveal transaction private key somewhere, so the user can intervene.
- Save a "recovery" transaction somewhere, that can be broadcast if the reveal transaction can't be mined that just returns coins to the wallet

**Comment by raphjaph** [comment]
- get bitcoin core to import descriptor of commit tx address/private key
- maybe even move signing of tx into bitcoin core (instead of generating private key ourselves)
  - `dumpprivkey`???
  - generate a descriptor and hand in script???

1. gen priv key
2. gen taproot descriptor for priv key
3.  import to bitcoin core
4.  ???

**Comment by raphjaph** [comment]
figure out taproot descriptors. 
What is a taproot descriptor for a single private key? with a tweaked private key?

**Comment by raphjaph** [comment]
rawtr(tweaked private key)

**Comment by raphjaph** [comment]
https://github.com/bitcoin/bitcoin/blob/master/doc/descriptors.md

Waiting for new release of bitcoin core

**Comment by casey** [comment]
@raphjaph Just a note on this one: As long as we can make sure that the wallet has the correct private key imported, and we're super sure of that, then getting it to sign with it can probably be deferred until later, since it isn't super important for the prototype inscription milestone.
