### ISSUE TITLE
Make it possible to build the index on a machine with 32 GiB of RAM

### ISSUE THREAD

**Issue by casey** [casey/ord#782]
The index builds quickly on machines with 64 GiB of RAM, but, at least from testing on @raphjaph's laptop, builds very slowly on machines with 32 GiB of RAM. This issue can be closed when the index can be built in less than 48 hours on a machine with 32 GiB of RAM.

- Determine optimization target. Why is it slow on machines with 32 GiB of RAM? We need easy, reproducible benchmarks that allow us to figure out what we should be optimizing.
- Can this be improved? I highly doubt that the working set size is greater than 32 GiB, but it's possible. If the working set size is really bigger than 32 GiB, then this can't be optimized.

**Comment by VirtuallyThere** [comment]
Will run a benchmark on the weekend comparing my 64 GiB Mac Studio against mz 16 GiB MacBook Pro.

**Comment by casey** [comment]
Nice, I'm super curious about what the source of the slowdown is, and what exactly is increasing RAM usage.

**Comment by casey** [comment]
This shouldn't be an issue now that indexing ordinal ranges is optional.
