### ISSUE TITLE
Collections

### ISSUE THREAD

**Issue by casey** [casey/ord#784]
It should be possible to make a series of related inscriptions:

- If an inscription is part of a collection, it should link to the collection page
- The collection page should link to all inscriptions in the collection
- The collection page should have some description about the collection
- It should be possible to nest collections. E.g. create a collection that contains multiple collections.
- Collections should have provenance. You should be able to see the scribe who created a collection, and see the collections issued by a scribe.
- It should be possible to make a collection closed-ended, e.g. guarantee that it isn't possible to issue more items.
- It should be possible link to an item in a collection by number or possibly name, e.g. - `/COLLECTION_SYMBOL/NUMBER` or `/COLLECTION_SYMBOL/NAME`.

Design sketch:

- Reuse prime ordinals from #783. A collection is just a prime ordinal, and all the inscriptions that it's made. 
- If you want to add a description to the collection, make an inscription on the prime ordinal used to issue the collection.
- If you want to close the collection, send the prime ordinal to an OP_RETURN. (I don't actually like this. It seems bad to force burning the prime ordinal of a collection. But, it's very simple.)

**Comment by haribosan** [comment]
Collectors that want to make their collections public are going to need their own identifier too, something that links to all their inscriptions. Not sure if there are more elegant ways to achieve this but a static bitcoin address could easily do the trick: collectors can re-use the same address each time they add a new inscription to their collection, thus making all their art publicly fall under the same ID / owner. In this context, address reuse is clearly a non issue. What could be an issue is the ability for anyone to spam known collectors by sending them bogus inscriptions. But I believe having a prime ordinal equivalent for collectors is a very important feature to have.

**Comment by casey** [comment]
@haribosan Thanks for the comment! Opened up #1189 to track this.

**Comment by casey** [comment]
Closing in favor of combined issue: #783.
