### ISSUE TITLE
Reenable and benchmark mainnet inscriptions

### ISSUE THREAD

**Issue by casey** [casey/ord#815]
We need to be making sure that inscription performance isn't terrible on mainnet, since we do plan on enabling it eventually. It's dangerous to leave it disabled, so we should re-enable it and make sure it's fast before we launch prototype inscriptions.

**Comment by VirtuallyThere** [comment]
See https://github.com/casey/ord/issues/813 - disabling the inscriptions roughly halves the time to index mainnet on my Mac. There still seems to be some other slowdown, so will investigate that in new issue https://github.com/casey/ord/issues/819

**Comment by casey** [comment]
Nice, thanks for the report. There's a lot we can do here, so reenabling it eventually should be no problem.

**Comment by casey** [comment]
Closing in favor of #798.
