### ISSUE TITLE
Explore putting inscriptions in non-script witness element

### ISSUE THREAD

**Issue by casey** [casey/ord#833]
Currently, inscriptions are stored in an un-executed `OP_FALSE OP_IF … OP_ENDIF` in the script. This has a number of downsides:

- Inscriptions must be parsed as scripts by full nodes. This is cheap, so not a huge downside.
- Inscriptions must respect the 520 byte data push size limit by chunking any data into multiple pushes.
- If script parsing rules change in the future, then we would have to update accordingly.

One alternative would be to store inscriptions directly in non-script witness elements. These witness elements would not be committed to by the taproot output key, so we would have to commit to the hash in the script, and include instructions to hash the element, compare the hash to the committed hash, and pop the witness element.

However, just in the course of writing this issue, I read that the 520 byte limit applies to the initial stack, and since left over witness elements are part of the initial stack, we can't get around it by sticking the inscription in the witness, and so the main motivation for doing this is gone. RIP this issue.

**Comment by raphjaph** [comment]
Always good to write stuff down. Forces oneself to be clear and discover holes in reasoning
