### ISSUE TITLE
Make it easy for other protocols to use the  OP_FALSE OP_IF construction

### ISSUE THREAD

**Issue by casey** [casey/ord#882]
Maybe include a magic number to indicate that it's an ordinal inscription, so that other applications can use different magic numbers.

**Comment by raphjaph** [comment]
Like before the MIME type?

**Comment by casey** [comment]
Yup, before the MIME type so the parser can immediately tell if it's an inscription or something else.

**Comment by casey** [comment]
This can be closed now that we added a magic number.
